// Generated by Rivet — do not edit

import { rivetFetch, type RivetResult } from "../rivet.js";

export function listOffers(input: { query: { subjectKey: string; }; }): Promise<void>;
export function listOffers(input: { query: { subjectKey: string; }; }, opts: { unwrap: true }): Promise<void>;
export function listOffers(input: { query: { subjectKey: string; }; }, opts: { unwrap: false }): Promise<RivetResult<void>>;
export function listOffers(input: { query: { subjectKey: string; }; }, opts?: { unwrap?: boolean }): Promise<void | RivetResult<void>> {
  return rivetFetch<RivetResult<void>>("GET", `/api/offers`, { query: input.query, unwrap: opts?.unwrap });
}
