using System.Text;
using System.Text.RegularExpressions;
using Rivet.Tool.Model;

namespace Rivet.Tool.Emit;

/// <summary>
/// Renders TsEndpointDefinitions to per-controller TypeScript client files.
/// </summary>
public static partial class ClientEmitter
{
    private static readonly Dictionary<string, string> ReservedWordReplacements = new()
    {
        ["delete"] = "remove",
    };

    /// <summary>
    /// Emits the shared rivet.ts module with rivetFetch + configureRivet.
    /// </summary>
    public static string EmitRivetBase()
    {
        var assembly = typeof(ClientEmitter).Assembly;
        var resourceName = assembly.GetManifestResourceNames()
            .FirstOrDefault(static name => name.EndsWith("rivet.ts", StringComparison.Ordinal));
        using var stream = resourceName is not null
            ? assembly.GetManifestResourceStream(resourceName)
            : null;
        if (stream is null)
        {
            throw new InvalidOperationException("Embedded resource ending with 'rivet.ts' not found.");
        }
        using var reader = new StreamReader(stream);
        return reader.ReadToEnd();
    }

    /// <summary>
    /// Emits a per-controller client file with typed fetch functions.
    /// </summary>
    public static string EmitControllerClient(
        string controllerName,
        IReadOnlyList<TsEndpointDefinition> endpoints,
        IReadOnlyDictionary<string, string> typeFileMap,
        ValidateMode validateMode = ValidateMode.None)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// Generated by Rivet — do not edit");
        sb.AppendLine();

        // Import rivetFetch + types from shared module
        var needsGetBaseUrl = endpoints.Any(e => e.QueryAuth is not null);
        var needsResultOf = endpoints.Any(e => e.Responses.Count >= 2);
        var rivetImports = needsGetBaseUrl
            ? needsResultOf
                ? "import { rivetFetch, getBaseUrl, type RivetResult, type RivetResultOf } from \"../rivet.js\";"
                : "import { rivetFetch, getBaseUrl, type RivetResult } from \"../rivet.js\";"
            : needsResultOf
                ? "import { rivetFetch, type RivetResult, type RivetResultOf } from \"../rivet.js\";"
                : "import { rivetFetch, type RivetResult } from \"../rivet.js\";";
        sb.AppendLine(rivetImports);

        // Import validator assertions
        if (validateMode == ValidateMode.Zod)
        {
            var assertImports = endpoints
                .Where(e => e.ReturnType is not null)
                .Select(e => ZodValidatorEmitter.GetAssertName(e.ReturnType!))
                .Concat(endpoints.SelectMany(e => e.Responses)
                    .Where(r => r.DataType is not null)
                    .Select(r => ZodValidatorEmitter.GetAssertName(r.DataType!)))
                .Distinct()
                .Order()
                .ToList();

            if (assertImports.Count > 0)
            {
                sb.AppendLine($"import {{ {string.Join(", ", assertImports)} }} from \"../validators.js\";");
            }
        }

        // Import referenced types from their source files
        var referencedTypes = CollectReferencedTypeNames(endpoints);
        if (referencedTypes.Count > 0)
        {
            var importsByFile = referencedTypes
                .Where(t => typeFileMap.ContainsKey(t))
                .GroupBy(t => typeFileMap[t])
                .OrderBy(g => g.Key);

            foreach (var group in importsByFile)
            {
                var names = string.Join(", ", group.Order());
                sb.AppendLine($"import type {{ {names} }} from \"../types/{group.Key}.js\";");
            }
        }

        // Emit each endpoint function
        foreach (var endpoint in endpoints)
        {
            sb.AppendLine();
            EmitEndpoint(sb, endpoint, validateMode);
        }

        return sb.ToString();
    }

    /// <summary>
    /// Groups endpoints by controller name.
    /// </summary>
    public static Dictionary<string, List<TsEndpointDefinition>> GroupByController(
        IReadOnlyList<TsEndpointDefinition> endpoints)
    {
        var groups = new Dictionary<string, List<TsEndpointDefinition>>();

        foreach (var endpoint in endpoints)
        {
            if (!groups.TryGetValue(endpoint.ControllerName, out var list))
            {
                list = new List<TsEndpointDefinition>();
                groups[endpoint.ControllerName] = list;
            }

            list.Add(endpoint);
        }

        return groups;
    }

    private static void EmitEndpoint(StringBuilder sb, TsEndpointDefinition endpoint, ValidateMode validateMode)
    {
        var funcName = SafeFunctionName(endpoint.Name);

        var isFileEndpoint = endpoint.FileContentType is not null;
        var successType = isFileEndpoint
            ? "Blob"
            : endpoint.ReturnType is not null
                ? TypeEmitter.EmitTypeString(endpoint.ReturnType)
                : "void";

        var routeParams = endpoint.Params.Where(p => p.Source == ParamSource.Route).ToList();
        var fileParams = endpoint.Params.Where(p => p.Source == ParamSource.File).ToList();
        var formFieldParams = endpoint.Params.Where(p => p.Source == ParamSource.FormField).ToList();
        var bodyParam = endpoint.Params.FirstOrDefault(p => p.Source == ParamSource.Body);
        var queryParams = endpoint.Params.Where(p => p.Source == ParamSource.Query).ToList();
        var requestBodyType = bodyParam is not null
            ? TypeEmitter.EmitTypeString(bodyParam.Type)
            : fileParams.Count == 0 && endpoint.RequestType is not null
                ? TypeEmitter.EmitTypeString(endpoint.RequestType)
                : null;

        var inputType = BuildInputType(routeParams, queryParams, fileParams, formFieldParams, requestBodyType);
        var paramsStr = inputType is not null ? $"input: {inputType}" : "";
        var route = InterpolateRoute(
            endpoint.RouteTemplate,
            routeParams,
            param => AccessProperty("input.params", param.Name));

        // Determine result type for unwrap: false
        var hasResultDU = endpoint.Responses.Count >= 2;
        var resultTypeName = hasResultDU
            ? $"{Naming.ToPascalCase(funcName)}Result"
            : $"RivetResult<{successType}>";

        // Emit result DU type for multi-response endpoints
        if (hasResultDU)
        {
            EmitResultType(sb, resultTypeName, endpoint.Responses, isFileEndpoint);
        }

        // Overload signatures
        var optsPrefix = paramsStr.Length > 0 ? $"{paramsStr}, " : "";
        sb.AppendLine($"export function {funcName}({paramsStr}): Promise<{successType}>;");
        sb.AppendLine($"export function {funcName}({optsPrefix}opts: {{ unwrap: true }}): Promise<{successType}>;");
        sb.AppendLine($"export function {funcName}({optsPrefix}opts: {{ unwrap: false }}): Promise<{resultTypeName}>;");

        // Build fetch options
        var fetchOptionParts = new List<string>();
        if (fileParams.Count > 0)
        {
            fetchOptionParts.Add("body: fd");
        }
        else if (bodyParam is not null || endpoint.RequestType is not null)
        {
            if (endpoint.IsFormEncoded)
            {
                fetchOptionParts.Add($"body: new URLSearchParams({AccessProperty("input", "body")} as Record<string, string>)");
                fetchOptionParts.Add("formEncoded: true");
            }
            else
            {
                fetchOptionParts.Add($"body: {AccessProperty("input", "body")}");
            }
        }
        if (queryParams.Count > 0)
        {
            fetchOptionParts.Add($"query: {AccessProperty("input", "query")}");
        }

        if (isFileEndpoint)
        {
            fetchOptionParts.Add("blob: true");
        }

        var baseFetchStr = fetchOptionParts.Count > 0
            ? $", {{ {string.Join(", ", fetchOptionParts)} }}"
            : "";

        fetchOptionParts.Add("unwrap: opts?.unwrap");
        var fullFetchStr = $", {{ {string.Join(", ", fetchOptionParts)} }}";

        var implReturn = $"Promise<{successType} | {resultTypeName}>";
        var hasTypedErrorResponses = endpoint.Responses.Any(r => r.DataType is not null && r.StatusCode >= 400);
        var needsValidation = validateMode != ValidateMode.None && (endpoint.ReturnType is not null || hasTypedErrorResponses);
        var needsAsync = fileParams.Count > 0 || needsValidation;
        var asyncKeyword = needsAsync ? "async " : "";

        // Implementation signature
        sb.AppendLine($"export {asyncKeyword}function {funcName}({optsPrefix}opts?: {{ unwrap?: boolean }}): {implReturn} {{");

        // FormData construction for file uploads
        if (fileParams.Count > 0)
        {
            sb.AppendLine("  const fd = new FormData();");
            foreach (var fp in fileParams)
            {
                sb.AppendLine($"  fd.append(\"{fp.Name}\", {AccessProperty("input.body", fp.Name)});");
            }
            foreach (var ff in formFieldParams)
            {
                if (ff.Type is TsType.Primitive p && p.Name == "string")
                {
                    sb.AppendLine($"  fd.append(\"{ff.Name}\", {AccessProperty("input.body", ff.Name)});");
                }
                else
                {
                    sb.AppendLine($"  fd.append(\"{ff.Name}\", JSON.stringify({AccessProperty("input.body", ff.Name)}));");
                }
            }
        }

        if (needsValidation)
        {
            // unwrap: false branch — validate error responses (and success if present)
            if (hasTypedErrorResponses)
            {
                sb.AppendLine($"  if (opts?.unwrap === false) {{");
                sb.AppendLine($"    const result = await rivetFetch<{resultTypeName}>(\"{endpoint.HttpMethod}\", `{route}`{fullFetchStr});");
                var responses = endpoint.Responses.Where(r => r.DataType is not null).ToList();
                for (var i = 0; i < responses.Count; i++)
                {
                    var responseAssert = ZodValidatorEmitter.GetAssertName(responses[i].DataType!);
                    var prefix = i == 0 ? "    if" : "    else if";
                    sb.AppendLine($"{prefix} (result.status === {responses[i].StatusCode}) {{");
                    sb.AppendLine($"      result.data = {responseAssert}(result.data);");
                    sb.AppendLine("      return result;");
                    sb.AppendLine("    }");
                }
                if (endpoint.ReturnType is not null)
                {
                    var successAssert = ZodValidatorEmitter.GetAssertName(endpoint.ReturnType);
                    sb.AppendLine("    else {");
                    sb.AppendLine($"      result.data = {successAssert}(result.data);");
                    sb.AppendLine("      return result;");
                    sb.AppendLine("    }");
                }
                else
                {
                    sb.AppendLine("    return result;");
                }
                sb.AppendLine("  }");
            }
            else if (endpoint.ReturnType is not null)
            {
                var assertName = ZodValidatorEmitter.GetAssertName(endpoint.ReturnType);
                sb.AppendLine($"  if (opts?.unwrap === false) {{");
                sb.AppendLine($"    const result = await rivetFetch<{resultTypeName}>(\"{endpoint.HttpMethod}\", `{route}`{fullFetchStr});");
                sb.AppendLine($"    result.data = {assertName}(result.data);");
                sb.AppendLine("    return result;");
                sb.AppendLine("  }");
            }

            // Unwrapped return — validate success type if present, otherwise plain fetch
            if (endpoint.ReturnType is not null)
            {
                var assertName = ZodValidatorEmitter.GetAssertName(endpoint.ReturnType);
                sb.AppendLine($"  const data = await rivetFetch<{successType}>(\"{endpoint.HttpMethod}\", `{route}`{baseFetchStr});");
                sb.AppendLine($"  return {assertName}(data);");
            }
            else
            {
                sb.AppendLine($"  return rivetFetch<{resultTypeName}>(\"{endpoint.HttpMethod}\", `{route}`{fullFetchStr});");
            }
        }
        else
        {
            sb.AppendLine($"  return rivetFetch<{resultTypeName}>(\"{endpoint.HttpMethod}\", `{route}`{fullFetchStr});");
        }

        sb.AppendLine("}");

        // Emit companion *Url() function for QueryAuth endpoints
        if (endpoint.QueryAuth is not null)
        {
            EmitUrlFunction(sb, endpoint);
        }
    }

    private static void EmitUrlFunction(StringBuilder sb, TsEndpointDefinition endpoint)
    {
        var funcName = SafeFunctionName(endpoint.Name);
        var urlFuncName = $"{funcName}Url";
        var routeParams = endpoint.Params.Where(p => p.Source == ParamSource.Route).ToList();
        var queryParams = endpoint.Params.Where(p => p.Source == ParamSource.Query).ToList();
        var route = InterpolateRoute(
            endpoint.RouteTemplate,
            routeParams,
            param => AccessProperty("input.params", param.Name));
        var queryAuthParam = endpoint.QueryAuth!.ParameterName;
        var inputType = BuildUrlInputType(routeParams, queryParams, queryAuthParam);

        // Build query string parts
        var queryParts = new List<string>();

        // Include existing query params
        foreach (var qp in queryParams)
        {
            queryParts.Add($"{qp.Name}=${{encodeURIComponent(String({AccessProperty("input.query", qp.Name)}))}}");
        }

        // Append the auth token
        queryParts.Add($"{queryAuthParam}=${{encodeURIComponent({AccessProperty("input.query", queryAuthParam)})}}");

        var queryString = string.Join("&", queryParts);

        sb.AppendLine();
        sb.AppendLine($"export function {urlFuncName}(input: {inputType}): string {{");
        sb.AppendLine($"  return `${{getBaseUrl()}}{route}?{queryString}`;");
        sb.AppendLine("}");
    }

    private static void EmitResultType(
        StringBuilder sb,
        string typeName,
        IReadOnlyList<TsResponseType> responses,
        bool isFileEndpoint = false)
    {
        var statusCodes = string.Join(" | ", responses.Select(r => r.StatusCode));
        sb.AppendLine($"export type {typeName} = RivetResultOf<");
        foreach (var r in responses)
        {
            // File endpoints: success responses (2xx with no DataType) carry Blob, not void
            var dataType = r.DataType is not null
                ? TypeEmitter.EmitTypeString(r.DataType)
                : isFileEndpoint && r.StatusCode is >= 200 and < 300
                    ? "Blob"
                    : "void";
            sb.AppendLine($"  | {{ status: {r.StatusCode}; data: {dataType}; response: Response }}");
        }
        sb.Append($"  | {{ status: Exclude<number, {statusCodes}>; data: unknown; response: Response }}");
        sb.AppendLine();
        sb.AppendLine(">;");
        sb.AppendLine();
    }

    private static string SafeFunctionName(string name)
    {
        if (ReservedWordReplacements.TryGetValue(name, out var replacement))
        {
            return replacement;
        }

        if (TsReservedWords.All.Contains(name))
        {
            return $"_{name}";
        }

        return name;
    }

    private static string? BuildInputType(
        IReadOnlyList<TsEndpointParam> routeParams,
        IReadOnlyList<TsEndpointParam> queryParams,
        IReadOnlyList<TsEndpointParam> fileParams,
        IReadOnlyList<TsEndpointParam> formFieldParams,
        string? requestBodyType)
    {
        var fields = new List<string>();

        if (routeParams.Count > 0)
        {
            fields.Add($"params: {BuildObjectType(routeParams)}");
        }

        if (queryParams.Count > 0)
        {
            fields.Add($"query: {BuildObjectType(queryParams)}");
        }

        if (fileParams.Count > 0 || formFieldParams.Count > 0)
        {
            fields.Add($"body: {BuildObjectType(fileParams.Concat(formFieldParams).ToList())}");
        }
        else if (requestBodyType is not null)
        {
            fields.Add($"body: {requestBodyType}");
        }

        return fields.Count > 0 ? $"{{ {string.Join("; ", fields)}; }}" : null;
    }

    private static string BuildUrlInputType(
        IReadOnlyList<TsEndpointParam> routeParams,
        IReadOnlyList<TsEndpointParam> queryParams,
        string queryAuthParam)
    {
        var fields = new List<string>();

        if (routeParams.Count > 0)
        {
            fields.Add($"params: {BuildObjectType(routeParams)}");
        }

        var queryShape = queryParams
            .Concat(new[] { new TsEndpointParam(queryAuthParam, new TsType.Primitive("string"), ParamSource.Query) })
            .ToList();
        fields.Add($"query: {BuildObjectType(queryShape)}");

        return $"{{ {string.Join("; ", fields)}; }}";
    }

    private static string BuildObjectType(IReadOnlyList<TsEndpointParam> parameters)
    {
        return $"{{ {string.Join("; ", parameters.Select(
            p => $"{TypeEmitter.QuoteIfNeeded(p.Name)}: {TypeEmitter.EmitTypeString(p.Type)}"))}; }}";
    }

    private static string InterpolateRoute(
        string template,
        IReadOnlyList<TsEndpointParam> routeParams,
        Func<TsEndpointParam, string> emitValue)
    {
        var result = RouteParamRegex().Replace(template, match =>
        {
            var paramName = match.Groups[1].Value;
            var param = routeParams.FirstOrDefault(p =>
                string.Equals(p.Name, paramName, StringComparison.OrdinalIgnoreCase));
            if (param is not null)
            {
                return $"${{encodeURIComponent(String({emitValue(param)}))}}";
            }

            throw new InvalidOperationException(
                $"Route placeholder '{{{paramName}}}' in '{template}' has no matching parameter in TInput. " +
                "Add a property with a matching name to the input type.");
        });

        return result;
    }

    private static string AccessProperty(string target, string propertyName)
    {
        var property = TypeEmitter.QuoteIfNeeded(propertyName);
        return property == propertyName
            ? $"{target}.{propertyName}"
            : $"{target}[{property}]";
    }

    private static HashSet<string> CollectReferencedTypeNames(IReadOnlyList<TsEndpointDefinition> endpoints)
    {
        var names = new HashSet<string>();

        foreach (var endpoint in endpoints)
        {
            foreach (var param in endpoint.Params)
            {
                TsType.CollectTypeRefs(param.Type, names);
            }

            if (endpoint.ReturnType is not null)
            {
                TsType.CollectTypeRefs(endpoint.ReturnType, names);
            }

            var bodyParam = endpoint.Params.FirstOrDefault(p => p.Source == ParamSource.Body);
            if (bodyParam is null && endpoint.RequestType is not null)
            {
                TsType.CollectTypeRefs(endpoint.RequestType, names);
            }

            foreach (var response in endpoint.Responses)
            {
                if (response.DataType is not null)
                {
                    TsType.CollectTypeRefs(response.DataType, names);
                }
            }
        }

        return names;
    }

    [GeneratedRegex(@"\{(\w+)\}")]
    private static partial Regex RouteParamRegex();
}
