using System.Text;
using System.Text.RegularExpressions;
using Rivet.Tool.Model;

namespace Rivet.Tool.Emit;

/// <summary>
/// Renders TsEndpointDefinitions to per-controller TypeScript client files.
/// </summary>
public static partial class ClientEmitter
{
    private static readonly HashSet<string> TsReservedWords = new()
    {
        "break", "case", "catch", "class", "const", "continue", "debugger",
        "default", "delete", "do", "else", "enum", "export", "extends",
        "false", "finally", "for", "function", "if", "import", "in",
        "instanceof", "new", "null", "return", "super", "switch", "this",
        "throw", "true", "try", "typeof", "var", "void", "while", "with",
        "yield", "let", "static", "implements", "interface", "package",
        "private", "protected", "public", "await", "async",
    };

    private static readonly Dictionary<string, string> ReservedWordReplacements = new()
    {
        ["delete"] = "remove",
    };

    /// <summary>
    /// Emits the shared rivet.ts module with rivetFetch + configureRivet.
    /// </summary>
    public static string EmitRivetBase()
    {
        var sb = new StringBuilder();
        sb.AppendLine("""
            // Generated by Rivet — do not edit

            export type RivetConfig = {
              baseUrl: string;
              headers?: () => Record<string, string> | Promise<Record<string, string>>;
              fetch?: typeof fetch;
            };

            export class RivetError extends Error {
              constructor(
                public readonly method: string,
                public readonly path: string,
                public readonly status: number,
                public readonly response: Response,
                public readonly body: string,
                options?: ErrorOptions,
              ) {
                super(`Rivet: ${method} ${path} returned ${status}`, options);
                this.name = "RivetError";
              }
            }

            let _config: RivetConfig = { baseUrl: "" };

            export const configureRivet = (config: RivetConfig): void => {
              _config = config;
            };

            export const rivetFetch = async <T>(
              method: string,
              path: string,
              options?: { body?: unknown; query?: Record<string, string> },
            ): Promise<T> => {
              const url = new URL(`${_config.baseUrl}${path}`);
              if (options?.query) {
                for (const [k, v] of Object.entries(options.query)) {
                  if (v != null) url.searchParams.set(k, v);
                }
              }
              const headers: Record<string, string> = {
                ...(await _config.headers?.()),
              };
              const isFormData = typeof FormData !== "undefined" && options?.body instanceof FormData;
              if (options?.body && !isFormData) {
                headers["Content-Type"] = "application/json";
              }
              const f = _config.fetch ?? fetch;
              let res: Response;
              try {
                res = await f(url.toString(), {
                  method,
                  headers,
                  body: options?.body ? (isFormData ? options.body as BodyInit : JSON.stringify(options.body)) : undefined,
                });
              } catch (err) {
                throw new RivetError(method, path, 0, undefined as unknown as Response, "", { cause: err });
              }
              if (!res.ok) {
                const body = await res.text().catch(() => "");
                throw new RivetError(method, path, res.status, res, body, {
                  cause: new Error(`HTTP ${res.status}`),
                });
              }
              if (res.status === 204) {
                return undefined as T;
              }
              return (await res.json()) as T;
            };
            """);

        return sb.ToString();
    }

    /// <summary>
    /// Emits a per-controller client file with typed fetch functions.
    /// </summary>
    public static string EmitControllerClient(
        string controllerName,
        IReadOnlyList<TsEndpointDefinition> endpoints,
        bool validated = false)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// Generated by Rivet — do not edit");
        sb.AppendLine();

        // Import rivetFetch + types from shared module
        sb.AppendLine("import { rivetFetch } from \"../rivet.js\";");

        // Import validator assertions from build output
        if (validated)
        {
            var assertImports = endpoints
                .Where(e => e.ReturnType is not null)
                .Select(e => ValidatorEmitter.GetAssertName(e.ReturnType!))
                .Distinct()
                .Order()
                .ToList();

            if (assertImports.Count > 0)
            {
                sb.AppendLine($"import {{ {string.Join(", ", assertImports)} }} from \"../build/validators.js\";");
            }
        }

        // Import referenced types from types.ts
        var referencedTypes = CollectReferencedTypeNames(endpoints);
        if (referencedTypes.Count > 0)
        {
            sb.AppendLine($"import type {{ {string.Join(", ", referencedTypes.Order())} }} from \"../types.js\";");
        }

        // Emit each endpoint function
        foreach (var endpoint in endpoints)
        {
            sb.AppendLine();
            EmitEndpoint(sb, endpoint, validated);
        }

        return sb.ToString();
    }

    /// <summary>
    /// Groups endpoints by controller name.
    /// </summary>
    public static Dictionary<string, List<TsEndpointDefinition>> GroupByController(
        IReadOnlyList<TsEndpointDefinition> endpoints)
    {
        var groups = new Dictionary<string, List<TsEndpointDefinition>>();

        foreach (var endpoint in endpoints)
        {
            if (!groups.TryGetValue(endpoint.ControllerName, out var list))
            {
                list = new List<TsEndpointDefinition>();
                groups[endpoint.ControllerName] = list;
            }

            list.Add(endpoint);
        }

        return groups;
    }

    /// <summary>
    /// Legacy: emit all endpoints into a single client.ts file.
    /// Used for backwards compat with existing tests and standalone mode.
    /// </summary>
    public static string Emit(
        IReadOnlyList<TsEndpointDefinition> endpoints,
        IReadOnlyList<TsTypeDefinition> types,
        bool validated = false)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// Generated by Rivet — do not edit");
        sb.AppendLine();

        if (validated)
        {
            var assertImports = endpoints
                .Where(e => e.ReturnType is not null)
                .Select(e => ValidatorEmitter.GetAssertName(e.ReturnType!))
                .Distinct()
                .Order()
                .ToList();

            if (assertImports.Count > 0)
            {
                sb.AppendLine($"import {{ {string.Join(", ", assertImports)} }} from \"./build/validators.js\";");
            }
        }

        var referencedTypes = CollectReferencedTypeNames(endpoints);
        if (referencedTypes.Count > 0)
        {
            sb.AppendLine($"import type {{ {string.Join(", ", referencedTypes.Order())} }} from \"./types.js\";");
            sb.AppendLine();
        }

        // Inline rivetFetch for single-file mode
        sb.AppendLine("export type RivetConfig = {");
        sb.AppendLine("  baseUrl: string;");
        sb.AppendLine("  headers?: () => Record<string, string> | Promise<Record<string, string>>;");
        sb.AppendLine("  fetch?: typeof fetch;");
        sb.AppendLine("};");
        sb.AppendLine();
        sb.AppendLine("let _config: RivetConfig = { baseUrl: \"\" };");
        sb.AppendLine();
        sb.AppendLine("export const configureRivet = (config: RivetConfig): void => {");
        sb.AppendLine("  _config = config;");
        sb.AppendLine("};");
        sb.AppendLine();
        sb.AppendLine("const rivetFetch = async <T>(");
        sb.AppendLine("  method: string,");
        sb.AppendLine("  path: string,");
        sb.AppendLine("  options?: { body?: unknown; query?: Record<string, string> },");
        sb.AppendLine("): Promise<T> => {");
        sb.AppendLine("  const url = new URL(`${_config.baseUrl}${path}`);");
        sb.AppendLine("  if (options?.query) {");
        sb.AppendLine("    for (const [k, v] of Object.entries(options.query)) {");
        sb.AppendLine("      url.searchParams.set(k, v);");
        sb.AppendLine("    }");
        sb.AppendLine("  }");
        sb.AppendLine("  const headers: Record<string, string> = {");
        sb.AppendLine("    ...(await _config.headers?.()),");
        sb.AppendLine("  };");
        sb.AppendLine("  if (options?.body) {");
        sb.AppendLine("    headers[\"Content-Type\"] = \"application/json\";");
        sb.AppendLine("  }");
        sb.AppendLine("  const f = _config.fetch ?? fetch;");
        sb.AppendLine("  const res = await f(url.toString(), {");
        sb.AppendLine("    method,");
        sb.AppendLine("    headers,");
        sb.AppendLine("    body: options?.body ? JSON.stringify(options.body) : undefined,");
        sb.AppendLine("  });");
        sb.AppendLine("  if (!res.ok) {");
        sb.AppendLine("    throw new Error(`Rivet: ${method} ${path} returned ${res.status}`);");
        sb.AppendLine("  }");
        sb.AppendLine("  if (res.status === 204) {");
        sb.AppendLine("    return undefined as T;");
        sb.AppendLine("  }");
        sb.AppendLine("  return (await res.json()) as T;");
        sb.AppendLine("};");

        foreach (var endpoint in endpoints)
        {
            sb.AppendLine();
            EmitEndpoint(sb, endpoint, validated);
        }

        return sb.ToString();
    }

    private static void EmitEndpoint(StringBuilder sb, TsEndpointDefinition endpoint, bool validated)
    {
        var funcName = SafeFunctionName(endpoint.Name);

        var successType = endpoint.ReturnType is not null
            ? TypeEmitter.EmitTypeString(endpoint.ReturnType)
            : "void";

        var paramParts = new List<string>();
        foreach (var p in endpoint.Params)
        {
            paramParts.Add($"{p.Name}: {TypeEmitter.EmitTypeString(p.Type)}");
        }

        var paramsStr = string.Join(", ", paramParts);

        var route = InterpolateRoute(endpoint.RouteTemplate, endpoint.Params);

        var fileParams = endpoint.Params.Where(p => p.Source == ParamSource.File).ToList();
        var bodyParam = endpoint.Params.FirstOrDefault(p => p.Source == ParamSource.Body);
        var queryParams = endpoint.Params.Where(p => p.Source == ParamSource.Query).ToList();

        var fetchGeneric = endpoint.ReturnType is not null ? successType : "void";

        // Multipart (IFormFile) endpoints — emit FormData construction
        if (fileParams.Count > 0)
        {
            sb.AppendLine($"export const {funcName} = async ({paramsStr}): Promise<{successType}> => {{");
            sb.AppendLine("  const fd = new FormData();");
            foreach (var fp in fileParams)
            {
                sb.AppendLine($"  fd.append(\"{fp.Name}\", {fp.Name});");
            }

            var multipartOptions = new List<string> { "body: fd" };
            if (queryParams.Count > 0)
            {
                var queryEntries = queryParams.Select(p => $"{p.Name}: String({p.Name})");
                multipartOptions.Add($"query: {{ {string.Join(", ", queryEntries)} }}");
            }
            var multipartOptionsStr = $", {{ {string.Join(", ", multipartOptions)} }}";

            if (validated && endpoint.ReturnType is not null)
            {
                var assertName = ValidatorEmitter.GetAssertName(endpoint.ReturnType);
                sb.AppendLine($"  const data = await rivetFetch<{fetchGeneric}>(\"{endpoint.HttpMethod}\", `{route}`{multipartOptionsStr});");
                sb.AppendLine($"  return {assertName}(data);");
            }
            else
            {
                sb.AppendLine($"  return rivetFetch<{fetchGeneric}>(\"{endpoint.HttpMethod}\", `{route}`{multipartOptionsStr});");
            }
            sb.AppendLine("};");
            return;
        }

        var optionsParts = new List<string>();
        if (bodyParam is not null)
        {
            optionsParts.Add($"body: {bodyParam.Name}");
        }
        if (queryParams.Count > 0)
        {
            var queryEntries = queryParams.Select(p => $"{p.Name}: String({p.Name})");
            optionsParts.Add($"query: {{ {string.Join(", ", queryEntries)} }}");
        }

        var optionsStr = optionsParts.Count > 0
            ? $", {{ {string.Join(", ", optionsParts)} }}"
            : "";

        if (validated && endpoint.ReturnType is not null)
        {
            var assertName = ValidatorEmitter.GetAssertName(endpoint.ReturnType);
            sb.AppendLine($"export const {funcName} = async ({paramsStr}): Promise<{successType}> => {{");
            sb.AppendLine($"  const data = await rivetFetch<{fetchGeneric}>(\"{endpoint.HttpMethod}\", `{route}`{optionsStr});");
            sb.AppendLine($"  return {assertName}(data);");
            sb.AppendLine("};");
        }
        else
        {
            sb.AppendLine($"export const {funcName} = ({paramsStr}): Promise<{successType}> =>");
            sb.AppendLine($"  rivetFetch<{fetchGeneric}>(\"{endpoint.HttpMethod}\", `{route}`{optionsStr});");
        }
    }

    private static string ToPascalCase(string name)
    {
        if (string.IsNullOrEmpty(name) || char.IsUpper(name[0]))
        {
            return name;
        }

        return char.ToUpperInvariant(name[0]) + name[1..];
    }

    private static string SafeFunctionName(string name)
    {
        if (ReservedWordReplacements.TryGetValue(name, out var replacement))
        {
            return replacement;
        }

        if (TsReservedWords.Contains(name))
        {
            return $"_{name}";
        }

        return name;
    }

    private static string InterpolateRoute(string template, IReadOnlyList<TsEndpointParam> allParams)
    {
        var routeParams = allParams.Where(p => p.Source == ParamSource.Route).ToList();

        return RouteParamRegex().Replace(template, match =>
        {
            var paramName = match.Groups[1].Value;
            var param = routeParams.FirstOrDefault(p =>
                string.Equals(p.Name, paramName, StringComparison.OrdinalIgnoreCase));
            return param is not null ? $"${{{param.Name}}}" : match.Value;
        });
    }

    private static HashSet<string> CollectReferencedTypeNames(IReadOnlyList<TsEndpointDefinition> endpoints)
    {
        var names = new HashSet<string>();

        foreach (var endpoint in endpoints)
        {
            foreach (var param in endpoint.Params)
            {
                CollectTypeRefs(param.Type, names);
            }

            if (endpoint.ReturnType is not null)
            {
                CollectTypeRefs(endpoint.ReturnType, names);
            }
        }

        return names;
    }

    private static void CollectTypeRefs(TsType type, HashSet<string> names)
    {
        switch (type)
        {
            case TsType.TypeRef r:
                names.Add(r.Name);
                break;
            case TsType.Nullable n:
                CollectTypeRefs(n.Inner, names);
                break;
            case TsType.Array a:
                CollectTypeRefs(a.Element, names);
                break;
            case TsType.Dictionary d:
                CollectTypeRefs(d.Value, names);
                break;
            case TsType.Generic g:
                names.Add(g.Name);
                foreach (var arg in g.TypeArguments)
                {
                    CollectTypeRefs(arg, names);
                }
                break;
            case TsType.Brand b:
                names.Add(b.Name);
                break;
        }
    }

    [GeneratedRegex(@"\{(\w+)\}")]
    private static partial Regex RouteParamRegex();
}
