using System.Text;
using System.Text.RegularExpressions;
using Rivet.Tool.Model;

namespace Rivet.Tool.Emit;

/// <summary>
/// Renders TsEndpointDefinitions to per-controller TypeScript client files.
/// </summary>
public static partial class ClientEmitter
{
    private static readonly HashSet<string> TsReservedWords = new()
    {
        "break", "case", "catch", "class", "const", "continue", "debugger",
        "default", "delete", "do", "else", "enum", "export", "extends",
        "false", "finally", "for", "function", "if", "import", "in",
        "instanceof", "new", "null", "return", "super", "switch", "this",
        "throw", "true", "try", "typeof", "var", "void", "while", "with",
        "yield", "let", "static", "implements", "interface", "package",
        "private", "protected", "public", "await", "async",
    };

    private static readonly Dictionary<string, string> ReservedWordReplacements = new()
    {
        ["delete"] = "remove",
    };

    /// <summary>
    /// Emits the shared rivet.ts module with rivetFetch + configureRivet.
    /// </summary>
    public static string EmitRivetBase()
    {
        var sb = new StringBuilder();
        sb.AppendLine("""
            // Generated by Rivet — do not edit

            export type RivetConfig = {
              baseUrl: string;
              headers?: () => Record<string, string> | Promise<Record<string, string>>;
              fetch?: typeof fetch;
              onError?: (error: RivetError) => void;
            };

            export type RivetResult<T> = { status: number; data: T; response: Response };

            export class RivetError extends Error {
              constructor(
                public readonly method: string,
                public readonly path: string,
                public readonly status: number,
                public readonly response: Response | undefined,
                public readonly body: unknown,
                options?: ErrorOptions,
              ) {
                super(`Rivet: ${method} ${path} returned ${status}`, options);
                this.name = "RivetError";
              }
            }

            let _config: RivetConfig = { baseUrl: "" };

            export const configureRivet = (config: RivetConfig): void => {
              _config = config;
            };

            const parseBody = async (res: Response): Promise<unknown> => {
              const text = await res.text().catch(() => "");
              if (!text) return undefined;
              const ct = res.headers.get("content-type") ?? "";
              if (ct.includes("application/json")) {
                try { return JSON.parse(text); } catch { return text; }
              }
              return text;
            };

            export const rivetFetch = async <T>(
              method: string,
              path: string,
              options?: { body?: unknown; query?: Record<string, unknown>; unwrap?: boolean; blob?: boolean },
            ): Promise<T> => {
              const url = new URL(`${_config.baseUrl}${path}`);
              if (options?.query) {
                for (const [k, v] of Object.entries(options.query)) {
                  if (v != null) url.searchParams.set(k, String(v));
                }
              }
              const headers: Record<string, string> = {
                ...(await _config.headers?.()),
              };
              const isFormData = typeof FormData !== "undefined" && options?.body instanceof FormData;
              if (options?.body != null && !isFormData) {
                headers["Content-Type"] = "application/json";
              }
              const f = _config.fetch ?? fetch;
              let res: Response;
              try {
                res = await f(url.toString(), {
                  method,
                  headers,
                  body: options?.body != null ? (isFormData ? options.body as BodyInit : JSON.stringify(options.body)) : undefined,
                });
              } catch (err) {
                const error = new RivetError(method, path, 0, undefined, undefined, { cause: err });
                if (_config.onError) _config.onError(error);
                throw error;
              }
              if (options?.unwrap === false) {
                const body = options?.blob && res.ok ? await res.blob() : await parseBody(res);
                return { status: res.status, data: body, response: res } as T;
              }
              if (!res.ok) {
                const body = await parseBody(res);
                const error = new RivetError(method, path, res.status, res, body, {
                  cause: new Error(`HTTP ${res.status}`),
                });
                if (_config.onError) _config.onError(error);
                throw error;
              }
              if (options?.blob) return (await res.blob()) as T;
              return (await parseBody(res)) as T;
            };
            """);

        return sb.ToString();
    }

    /// <summary>
    /// Emits a per-controller client file with typed fetch functions.
    /// </summary>
    public static string EmitControllerClient(
        string controllerName,
        IReadOnlyList<TsEndpointDefinition> endpoints,
        IReadOnlyDictionary<string, string> typeFileMap,
        ValidateMode validateMode = ValidateMode.None)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// Generated by Rivet — do not edit");
        sb.AppendLine();

        // Import rivetFetch + types from shared module
        sb.AppendLine("import { rivetFetch, type RivetResult } from \"../rivet.js\";");

        // Import validator assertions
        if (validateMode is ValidateMode.Typia or ValidateMode.Zod)
        {
            var assertImports = endpoints
                .Where(e => e.ReturnType is not null)
                .Select(e => ValidatorEmitter.GetAssertName(e.ReturnType!))
                .Concat(endpoints.SelectMany(e => e.Responses)
                    .Where(r => r.DataType is not null)
                    .Select(r => ValidatorEmitter.GetAssertName(r.DataType!)))
                .Distinct()
                .Order()
                .ToList();

            if (assertImports.Count > 0)
            {
                var validatorPath = validateMode == ValidateMode.Typia
                    ? "../build/validators.js"
                    : "../validators.js";
                sb.AppendLine($"import {{ {string.Join(", ", assertImports)} }} from \"{validatorPath}\";");
            }
        }

        // Import referenced types from their source files
        var referencedTypes = CollectReferencedTypeNames(endpoints);
        if (referencedTypes.Count > 0)
        {
            var importsByFile = referencedTypes
                .Where(t => typeFileMap.ContainsKey(t))
                .GroupBy(t => typeFileMap[t])
                .OrderBy(g => g.Key);

            foreach (var group in importsByFile)
            {
                var names = string.Join(", ", group.Order());
                sb.AppendLine($"import type {{ {names} }} from \"../types/{group.Key}.js\";");
            }
        }

        // Emit each endpoint function
        foreach (var endpoint in endpoints)
        {
            sb.AppendLine();
            EmitEndpoint(sb, endpoint, validateMode);
        }

        return sb.ToString();
    }

    /// <summary>
    /// Groups endpoints by controller name.
    /// </summary>
    public static Dictionary<string, List<TsEndpointDefinition>> GroupByController(
        IReadOnlyList<TsEndpointDefinition> endpoints)
    {
        var groups = new Dictionary<string, List<TsEndpointDefinition>>();

        foreach (var endpoint in endpoints)
        {
            if (!groups.TryGetValue(endpoint.ControllerName, out var list))
            {
                list = new List<TsEndpointDefinition>();
                groups[endpoint.ControllerName] = list;
            }

            list.Add(endpoint);
        }

        return groups;
    }

    private static void EmitEndpoint(StringBuilder sb, TsEndpointDefinition endpoint, ValidateMode validateMode)
    {
        var funcName = SafeFunctionName(endpoint.Name);

        var isFileEndpoint = endpoint.FileContentType is not null;
        var successType = isFileEndpoint
            ? "Blob"
            : endpoint.ReturnType is not null
                ? TypeEmitter.EmitTypeString(endpoint.ReturnType)
                : "void";

        var paramParts = new List<string>();
        foreach (var p in endpoint.Params)
        {
            paramParts.Add($"{SafeParameterName(p.Name)}: {TypeEmitter.EmitTypeString(p.Type)}");
        }

        var paramsStr = string.Join(", ", paramParts);

        var route = InterpolateRoute(endpoint.RouteTemplate, endpoint.Params);

        var fileParams = endpoint.Params.Where(p => p.Source == ParamSource.File).ToList();
        var formFieldParams = endpoint.Params.Where(p => p.Source == ParamSource.FormField).ToList();
        var bodyParam = endpoint.Params.FirstOrDefault(p => p.Source == ParamSource.Body);
        var queryParams = endpoint.Params.Where(p => p.Source == ParamSource.Query).ToList();

        // Determine result type for unwrap: false
        var hasResultDU = endpoint.Responses.Count >= 2;
        var resultTypeName = hasResultDU
            ? $"{Naming.ToPascalCase(funcName)}Result"
            : $"RivetResult<{successType}>";

        // Emit result DU type for multi-response endpoints
        if (hasResultDU)
        {
            EmitResultType(sb, resultTypeName, endpoint.Responses, isFileEndpoint);
        }

        // Overload signatures
        var optsPrefix = paramsStr.Length > 0 ? $"{paramsStr}, " : "";
        sb.AppendLine($"export function {funcName}({paramsStr}): Promise<{successType}>;");
        sb.AppendLine($"export function {funcName}({optsPrefix}opts: {{ unwrap: true }}): Promise<{successType}>;");
        sb.AppendLine($"export function {funcName}({optsPrefix}opts: {{ unwrap: false }}): Promise<{resultTypeName}>;");

        // Build fetch options
        var fetchOptionParts = new List<string>();
        if (fileParams.Count > 0)
        {
            fetchOptionParts.Add("body: fd");
        }
        else if (bodyParam is not null)
        {
            fetchOptionParts.Add($"body: {SafeParameterName(bodyParam.Name)}");
        }
        if (queryParams.Count > 0)
        {
            var queryEntries = queryParams.Select(p =>
            {
                var safe = SafeParameterName(p.Name);
                return safe == p.Name ? p.Name : $"{p.Name}: {safe}";
            });
            fetchOptionParts.Add($"query: {{ {string.Join(", ", queryEntries)} }}");
        }

        if (isFileEndpoint)
        {
            fetchOptionParts.Add("blob: true");
        }

        var baseFetchStr = fetchOptionParts.Count > 0
            ? $", {{ {string.Join(", ", fetchOptionParts)} }}"
            : "";

        fetchOptionParts.Add("unwrap: opts?.unwrap");
        var fullFetchStr = $", {{ {string.Join(", ", fetchOptionParts)} }}";

        var implReturn = $"Promise<{successType} | {resultTypeName}>";
        var hasTypedErrorResponses = endpoint.Responses.Any(r => r.DataType is not null && r.StatusCode >= 400);
        var needsValidation = validateMode != ValidateMode.None && (endpoint.ReturnType is not null || hasTypedErrorResponses);
        var needsAsync = fileParams.Count > 0 || needsValidation;
        var asyncKeyword = needsAsync ? "async " : "";

        // Implementation signature
        sb.AppendLine($"export {asyncKeyword}function {funcName}({optsPrefix}opts?: {{ unwrap?: boolean }}): {implReturn} {{");

        // FormData construction for file uploads
        if (fileParams.Count > 0)
        {
            sb.AppendLine("  const fd = new FormData();");
            foreach (var fp in fileParams)
            {
                sb.AppendLine($"  fd.append(\"{fp.Name}\", {SafeParameterName(fp.Name)});");
            }
            foreach (var ff in formFieldParams)
            {
                var safeName = SafeParameterName(ff.Name);
                if (ff.Type is TsType.Primitive p && p.Name == "string")
                {
                    sb.AppendLine($"  fd.append(\"{ff.Name}\", {safeName});");
                }
                else
                {
                    sb.AppendLine($"  fd.append(\"{ff.Name}\", JSON.stringify({safeName}));");
                }
            }
        }

        if (needsValidation)
        {
            // unwrap: false branch — validate error responses (and success if present)
            if (hasTypedErrorResponses)
            {
                sb.AppendLine($"  if (opts?.unwrap === false) {{");
                sb.AppendLine($"    const result = await rivetFetch<{resultTypeName}>(\"{endpoint.HttpMethod}\", `{route}`{fullFetchStr});");
                var responses = endpoint.Responses.Where(r => r.DataType is not null).ToList();
                for (var i = 0; i < responses.Count; i++)
                {
                    var responseAssert = ValidatorEmitter.GetAssertName(responses[i].DataType!);
                    var prefix = i == 0 ? "    if" : "    else if";
                    sb.AppendLine($"{prefix} (result.status === {responses[i].StatusCode}) (result as any).data = {responseAssert}(result.data);");
                }
                if (endpoint.ReturnType is not null)
                {
                    var successAssert = ValidatorEmitter.GetAssertName(endpoint.ReturnType);
                    sb.AppendLine($"    else (result as any).data = {successAssert}(result.data);");
                }
                sb.AppendLine("    return result;");
                sb.AppendLine("  }");
            }
            else if (endpoint.ReturnType is not null)
            {
                var assertName = ValidatorEmitter.GetAssertName(endpoint.ReturnType);
                sb.AppendLine($"  if (opts?.unwrap === false) {{");
                sb.AppendLine($"    const result = await rivetFetch<{resultTypeName}>(\"{endpoint.HttpMethod}\", `{route}`{fullFetchStr});");
                sb.AppendLine($"    result.data = {assertName}(result.data);");
                sb.AppendLine("    return result;");
                sb.AppendLine("  }");
            }

            // Unwrapped return — validate success type if present, otherwise plain fetch
            if (endpoint.ReturnType is not null)
            {
                var assertName = ValidatorEmitter.GetAssertName(endpoint.ReturnType);
                sb.AppendLine($"  const data = await rivetFetch<{successType}>(\"{endpoint.HttpMethod}\", `{route}`{baseFetchStr});");
                sb.AppendLine($"  return {assertName}(data);");
            }
            else
            {
                sb.AppendLine($"  return rivetFetch<{resultTypeName}>(\"{endpoint.HttpMethod}\", `{route}`{fullFetchStr});");
            }
        }
        else
        {
            sb.AppendLine($"  return rivetFetch<{resultTypeName}>(\"{endpoint.HttpMethod}\", `{route}`{fullFetchStr});");
        }

        sb.AppendLine("}");
    }

    private static void EmitResultType(
        StringBuilder sb,
        string typeName,
        IReadOnlyList<TsResponseType> responses,
        bool isFileEndpoint = false)
    {
        var statusCodes = string.Join(" | ", responses.Select(r => r.StatusCode));
        sb.Append($"export type {typeName} =");
        foreach (var r in responses)
        {
            // File endpoints: success responses (2xx with no DataType) carry Blob, not void
            var dataType = r.DataType is not null
                ? TypeEmitter.EmitTypeString(r.DataType)
                : isFileEndpoint && r.StatusCode is >= 200 and < 300
                    ? "Blob"
                    : "void";
            sb.AppendLine();
            sb.Append($"  | {{ status: {r.StatusCode}; data: {dataType}; response: Response }}");
        }
        sb.AppendLine();
        sb.Append($"  | {{ status: Exclude<number, {statusCodes}>; data: unknown; response: Response }}");
        sb.AppendLine(";");
        sb.AppendLine();
    }

    private static string SafeFunctionName(string name)
    {
        if (ReservedWordReplacements.TryGetValue(name, out var replacement))
        {
            return replacement;
        }

        if (TsReservedWords.Contains(name))
        {
            return $"_{name}";
        }

        return name;
    }

    private static string SafeParameterName(string name)
    {
        if (TsReservedWords.Contains(name))
        {
            return $"_{name}";
        }

        return name;
    }

    private static string InterpolateRoute(string template, IReadOnlyList<TsEndpointParam> allParams)
    {
        var routeParams = allParams.Where(p => p.Source == ParamSource.Route).ToList();

        var result = RouteParamRegex().Replace(template, match =>
        {
            var paramName = match.Groups[1].Value;
            var param = routeParams.FirstOrDefault(p =>
                string.Equals(p.Name, paramName, StringComparison.OrdinalIgnoreCase));
            if (param is not null)
            {
                return $"${{{SafeParameterName(param.Name)}}}";
            }

            Console.Error.WriteLine($"warning: unmatched route placeholder '{{{paramName}}}' in '{template}'");
            return $"${{\"\" /* unmatched: {paramName} */}}";
        });

        return result;
    }

    private static HashSet<string> CollectReferencedTypeNames(IReadOnlyList<TsEndpointDefinition> endpoints)
    {
        var names = new HashSet<string>();

        foreach (var endpoint in endpoints)
        {
            foreach (var param in endpoint.Params)
            {
                TsType.CollectTypeRefs(param.Type, names);
            }

            if (endpoint.ReturnType is not null)
            {
                TsType.CollectTypeRefs(endpoint.ReturnType, names);
            }

            foreach (var response in endpoint.Responses)
            {
                if (response.DataType is not null)
                {
                    TsType.CollectTypeRefs(response.DataType, names);
                }
            }
        }

        return names;
    }

    [GeneratedRegex(@"\{(\w+)\}")]
    private static partial Regex RouteParamRegex();
}
