using System.Text.Json;
using Rivet.Tool.Model;

namespace Rivet.Tool.Emit;

/// <summary>
/// Emits standalone JSON Schema definitions as a TypeScript file.
/// Each exported const is a self-contained JSON Schema document with embedded $defs.
/// </summary>
public static class JsonSchemaEmitter
{
    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        WriteIndented = true,
        PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
    };

    public static string Emit(
        IReadOnlyDictionary<string, TsTypeDefinition> definitions,
        IReadOnlyDictionary<string, TsType.Brand> brands,
        IReadOnlyDictionary<string, TsType.StringUnion> enums)
    {
        var defs = new Dictionary<string, object>();

        // Object types (skip generic templates — they're emitted as monomorphised variants)
        foreach (var (name, def) in definitions)
        {
            if (def.TypeParameters.Count > 0)
            {
                continue;
            }

            defs[name] = BuildObjectSchema(def);
        }

        // Monomorphised generics: find all Generic type refs used in definitions
        var genericInstances = new Dictionary<string, TsType.Generic>();
        CollectAllGenericInstances(definitions, genericInstances);

        foreach (var (monoName, generic) in genericInstances)
        {
            if (!definitions.TryGetValue(generic.Name, out var genericDef))
            {
                continue;
            }

            var typeParamMap = new Dictionary<string, TsType>();
            for (var i = 0; i < Math.Min(genericDef.TypeParameters.Count, generic.TypeArguments.Count); i++)
            {
                typeParamMap[genericDef.TypeParameters[i]] = generic.TypeArguments[i];
            }

            defs[monoName] = BuildMonomorphisedSchema(genericDef, typeParamMap);
        }

        // Brands: emit inner type schema under brand name
        foreach (var (name, brand) in brands)
        {
            defs[name] = MapTsTypeToSchema(brand.Inner);
        }

        // Enums
        foreach (var (name, su) in enums)
        {
            defs[name] = new Dictionary<string, object>
            {
                ["type"] = "string",
                ["enum"] = su.Members.ToList(),
            };
        }

        // Build the output
        var sb = new System.Text.StringBuilder();
        sb.AppendLine("// Generated by Rivet — do not edit");
        sb.AppendLine();

        var defsJson = JsonSerializer.Serialize(defs, JsonOptions);
        sb.AppendLine($"const $defs = {defsJson} as const;");

        // One export per type in $defs
        foreach (var name in defs.Keys)
        {
            sb.AppendLine();
            sb.AppendLine($"export const {name}Schema = {{ \"$ref\": \"#/$defs/{name}\", \"$defs\": $defs }} as const;");
        }

        return sb.ToString();
    }

    internal static Dictionary<string, object> MapTsTypeToSchema(TsType type)
    {
        return type switch
        {
            TsType.Primitive p => MapPrimitive(p),

            TsType.Nullable n => new Dictionary<string, object>
            {
                ["anyOf"] = new List<object>
                {
                    MapTsTypeToSchema(n.Inner),
                    new Dictionary<string, object> { ["type"] = "null" },
                },
            },

            TsType.Array a => new Dictionary<string, object>
            {
                ["type"] = "array",
                ["items"] = MapTsTypeToSchema(a.Element),
            },

            TsType.Dictionary d => new Dictionary<string, object>
            {
                ["type"] = "object",
                ["additionalProperties"] = MapTsTypeToSchema(d.Value),
            },

            TsType.StringUnion su => new Dictionary<string, object>
            {
                ["type"] = "string",
                ["enum"] = su.Members.ToList(),
            },

            TsType.TypeRef r => new Dictionary<string, object>
            {
                ["$ref"] = $"#/$defs/{r.Name}",
            },

            TsType.Generic g => new Dictionary<string, object>
            {
                ["$ref"] = $"#/$defs/{MonomorphisedName(g)}",
            },

            TsType.Brand b => MapTsTypeToSchema(b.Inner),

            TsType.TypeParam tp => FallbackTypeParam(tp),

            TsType.InlineObject obj => BuildInlineObjectSchema(obj),

            _ => new Dictionary<string, object>(),
        };
    }

    private static Dictionary<string, object> MapPrimitive(TsType.Primitive p)
    {
        if (p.Name == "unknown")
        {
            return new Dictionary<string, object>();
        }

        return new Dictionary<string, object>
        {
            ["type"] = p.Name,
        };
    }

    private static Dictionary<string, object> FallbackTypeParam(TsType.TypeParam tp)
    {
        Console.Error.WriteLine($"warning: unresolved type parameter '{tp.Name}' in JSON Schema — emitting as empty schema");
        return new Dictionary<string, object>();
    }

    private static Dictionary<string, object> BuildObjectSchema(TsTypeDefinition def)
    {
        var properties = new Dictionary<string, object>();
        var required = new List<string>();

        foreach (var prop in def.Properties)
        {
            properties[prop.Name] = MapTsTypeToSchema(prop.Type);

            if (!prop.IsOptional)
            {
                required.Add(prop.Name);
            }
        }

        var schema = new Dictionary<string, object>
        {
            ["type"] = "object",
            ["properties"] = properties,
        };

        if (required.Count > 0)
        {
            schema["required"] = required;
        }

        return schema;
    }

    private static Dictionary<string, object> BuildMonomorphisedSchema(
        TsTypeDefinition genericDef,
        Dictionary<string, TsType> typeParamMap)
    {
        var properties = new Dictionary<string, object>();
        var required = new List<string>();

        foreach (var prop in genericDef.Properties)
        {
            var resolvedType = ResolveTypeParams(prop.Type, typeParamMap);
            properties[prop.Name] = MapTsTypeToSchema(resolvedType);

            if (!prop.IsOptional)
            {
                required.Add(prop.Name);
            }
        }

        var schema = new Dictionary<string, object>
        {
            ["type"] = "object",
            ["properties"] = properties,
        };

        if (required.Count > 0)
        {
            schema["required"] = required;
        }

        return schema;
    }

    private static Dictionary<string, object> BuildInlineObjectSchema(TsType.InlineObject obj)
    {
        var properties = new Dictionary<string, object>();
        var required = new List<string>();

        foreach (var (name, fieldType) in obj.Fields)
        {
            properties[name] = MapTsTypeToSchema(fieldType);
            required.Add(name);
        }

        var schema = new Dictionary<string, object>
        {
            ["type"] = "object",
            ["properties"] = properties,
        };

        if (required.Count > 0)
        {
            schema["required"] = required;
        }

        return schema;
    }

    private static TsType ResolveTypeParams(TsType type, Dictionary<string, TsType> map)
    {
        return type switch
        {
            TsType.TypeParam tp when map.TryGetValue(tp.Name, out var resolved) => resolved,
            TsType.Array a => new TsType.Array(ResolveTypeParams(a.Element, map)),
            TsType.Nullable n => new TsType.Nullable(ResolveTypeParams(n.Inner, map)),
            TsType.Dictionary d => new TsType.Dictionary(ResolveTypeParams(d.Value, map)),
            _ => type,
        };
    }

    private static void CollectAllGenericInstances(
        IReadOnlyDictionary<string, TsTypeDefinition> definitions,
        Dictionary<string, TsType.Generic> genericInstances)
    {
        foreach (var (_, def) in definitions)
        {
            foreach (var prop in def.Properties)
            {
                CollectGenericsFromType(prop.Type, genericInstances);
            }
        }
    }

    private static void CollectGenericsFromType(TsType type, Dictionary<string, TsType.Generic> instances)
    {
        switch (type)
        {
            case TsType.Generic g:
                instances.TryAdd(MonomorphisedName(g), g);
                foreach (var arg in g.TypeArguments)
                {
                    CollectGenericsFromType(arg, instances);
                }
                break;
            case TsType.Array a:
                CollectGenericsFromType(a.Element, instances);
                break;
            case TsType.Nullable n:
                CollectGenericsFromType(n.Inner, instances);
                break;
            case TsType.Dictionary d:
                CollectGenericsFromType(d.Value, instances);
                break;
            case TsType.InlineObject obj:
                foreach (var (_, fieldType) in obj.Fields)
                {
                    CollectGenericsFromType(fieldType, instances);
                }
                break;
        }
    }

    internal static string MonomorphisedName(TsType.Generic g)
    {
        return g.Name + string.Concat(g.TypeArguments.Select(GetTypeNameSuffix));
    }

    private static string GetTypeNameSuffix(TsType type)
    {
        return type switch
        {
            TsType.TypeRef r => r.Name,
            TsType.TypeParam tp => tp.Name,
            TsType.Primitive p => UpperFirst(p.Name),
            TsType.Generic g => MonomorphisedName(g),
            TsType.Array a => GetTypeNameSuffix(a.Element) + "Array",
            TsType.Nullable n => GetTypeNameSuffix(n.Inner) + "Nullable",
            TsType.Brand b => b.Name,
            _ => "Unknown",
        };
    }

    private static string UpperFirst(string s) => Naming.ToPascalCase(s);
}
