using System.Text;
using Rivet.Tool.Model;

namespace Rivet.Tool.Emit;

/// <summary>
/// Renders TsTypeDefinitions to a TypeScript types.ts file.
/// </summary>
public static class TypeEmitter
{
    public static string Emit(
        IReadOnlyList<TsTypeDefinition> definitions,
        IReadOnlyList<TsType.Brand>? brands = null)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// Generated by Rivet — do not edit");
        sb.AppendLine();

        // Emit branded VO types first
        if (brands is { Count: > 0 })
        {
            foreach (var brand in brands)
            {
                var inner = EmitType(brand.Inner);
                sb.AppendLine($"export type {brand.Name} = {inner} & {{ readonly __brand: \"{brand.Name}\" }};");
            }

            sb.AppendLine();
        }

        for (var i = 0; i < definitions.Count; i++)
        {
            if (i > 0)
            {
                sb.AppendLine();
            }

            EmitDefinition(sb, definitions[i]);
        }

        return sb.ToString();
    }

    private static void EmitDefinition(StringBuilder sb, TsTypeDefinition definition)
    {
        var typeParams = definition.TypeParameters.Count > 0
            ? $"<{string.Join(", ", definition.TypeParameters)}>"
            : "";
        sb.AppendLine($"export type {definition.Name}{typeParams} = {{");

        foreach (var prop in definition.Properties)
        {
            var optional = prop.IsOptional ? "?" : "";
            var typeStr = EmitType(prop.Type);
            sb.AppendLine($"  {prop.Name}{optional}: {typeStr};");
        }

        sb.AppendLine("};");
    }

    /// <summary>
    /// Renders a TsType to its TypeScript string representation.
    /// Used by both TypeEmitter and ClientEmitter.
    /// </summary>
    public static string EmitTypeString(TsType type) => EmitType(type);

    private static string EmitType(TsType type) =>
        type switch
        {
            TsType.Primitive p => p.Name,
            TsType.Nullable n => $"{EmitType(n.Inner)} | null",
            TsType.Array a => WrapIfCompound(a.Element) + "[]",
            TsType.Dictionary d => $"Record<string, {EmitType(d.Value)}>",
            TsType.StringUnion u => string.Join(" | ", u.Members.Select(m => $"\"{m}\"")),
            TsType.TypeRef r => r.Name,
            TsType.Generic g => $"{g.Name}<{string.Join(", ", g.TypeArguments.Select(EmitType))}>",
            TsType.Brand b => b.Name,
            _ => "unknown",
        };

    /// <summary>
    /// Wraps compound types (union, nullable) in parens when used as array element.
    /// e.g. (string | null)[] not string | null[]
    /// </summary>
    private static string WrapIfCompound(TsType element)
    {
        var str = EmitType(element);
        return element is TsType.Nullable or TsType.StringUnion
            ? $"({str})"
            : str;
    }
}
