using System.Text;
using System.Text.RegularExpressions;
using Rivet.Tool.Model;

namespace Rivet.Tool.Emit;

/// <summary>
/// Renders TsTypeDefinitions to a TypeScript types.ts file.
/// </summary>
public static class TypeEmitter
{
    private static void EmitDefinition(StringBuilder sb, TsTypeDefinition definition)
    {
        var typeParams = definition.TypeParameters.Count > 0
            ? $"<{string.Join(", ", definition.TypeParameters)}>"
            : "";
        sb.AppendLine($"export type {definition.Name}{typeParams} = {{");

        foreach (var prop in definition.Properties)
        {
            var optional = prop.IsOptional ? "?" : "";
            var typeStr = EmitType(prop.Type);
            sb.AppendLine($"  {QuoteIfNeeded(prop.Name)}{optional}: {typeStr};");
        }

        sb.AppendLine("};");
    }

    /// <summary>
    /// Renders a TsType to its TypeScript string representation.
    /// Used by both TypeEmitter and ClientEmitter.
    /// </summary>
    public static string EmitTypeString(TsType type) => EmitType(type);

    private static string EmitType(TsType type) =>
        type switch
        {
            TsType.Primitive p => p.Name,
            TsType.TypeParam tp => tp.Name,
            TsType.Nullable n => $"{EmitType(n.Inner)} | null",
            TsType.Array a => WrapIfCompound(a.Element) + "[]",
            TsType.Dictionary d => $"Record<string, {EmitType(d.Value)}>",
            TsType.StringUnion u => string.Join(" | ", u.Members.Select(m => $"\"{m}\"")),
            TsType.IntUnion iu => string.Join(" | ", iu.Members),
            TsType.TypeRef r => r.Name,
            TsType.Generic g => $"{g.Name}<{string.Join(", ", g.TypeArguments.Select(EmitType))}>",
            TsType.Brand b => b.Name,
            TsType.InlineObject obj => $"{{ {string.Join("; ", obj.Fields.Select(f => $"{QuoteIfNeeded(f.Name)}: {EmitType(f.Type)}"))}; }}",
            _ => "unknown",
        };

    /// <summary>
    /// Emits a single group file with imports from other group files.
    /// </summary>
    public static string EmitGroupFile(TypeGrouper.TypeFileGroup group)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// Generated by Rivet — do not edit");
        sb.AppendLine();

        // Emit imports from other group files
        foreach (var (sourceFile, typeNames) in group.Imports.OrderBy(x => x.Key))
        {
            sb.AppendLine($"import type {{ {string.Join(", ", typeNames)} }} from \"./{sourceFile}.js\";");
        }

        if (group.Imports.Count > 0)
        {
            sb.AppendLine();
        }

        // Brands
        if (group.Brands.Count > 0)
        {
            foreach (var brand in group.Brands)
            {
                var inner = EmitType(brand.Inner);
                sb.AppendLine($"export type {brand.Name} = {inner} & {{ readonly __brand: \"{brand.Name}\" }};");
            }

            sb.AppendLine();
        }

        // Enums
        if (group.Enums.Count > 0)
        {
            foreach (var (name, enumType) in group.Enums.OrderBy(e => e.Key))
            {
                sb.AppendLine($"export type {name} = {EmitType(enumType)};");
            }

            sb.AppendLine();
        }

        // Definitions
        for (var i = 0; i < group.Definitions.Count; i++)
        {
            if (i > 0)
            {
                sb.AppendLine();
            }

            EmitDefinition(sb, group.Definitions[i]);
        }

        return sb.ToString();
    }

    /// <summary>
    /// Emits a barrel index.ts with namespaced re-exports (export * as name).
    /// </summary>
    public static string EmitNamespacedBarrel(IReadOnlyList<string> fileNames)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// Generated by Rivet — do not edit");
        sb.AppendLine();

        foreach (var fileName in fileNames.Order())
        {
            sb.AppendLine($"export * as {fileName} from \"./{fileName}.js\";");
        }

        return sb.ToString();
    }

    private static readonly Regex ValidIdentifier = new(@"^[a-zA-Z_$][a-zA-Z0-9_$]*$", RegexOptions.Compiled);

    internal static string QuoteIfNeeded(string name)
    {
        return ValidIdentifier.IsMatch(name) ? name : $"\"{name}\"";
    }

    /// <summary>
    /// Wraps compound types (union, nullable) in parens when used as array element.
    /// e.g. (string | null)[] not string | null[]
    /// </summary>
    private static string WrapIfCompound(TsType element)
    {
        var str = EmitType(element);
        return element is TsType.Nullable or TsType.StringUnion or TsType.IntUnion
            ? $"({str})"
            : str;
    }
}
