using System.Text;
using Rivet.Tool.Model;

namespace Rivet.Tool.Emit;

/// <summary>
/// Emits validators.ts with typia.createAssert&lt;T&gt;() calls for each
/// endpoint return type. This file is inert until compiled by tsc + typia.
/// </summary>
public static class ValidatorEmitter
{
    public static string Emit(
        IReadOnlyList<TsEndpointDefinition> endpoints,
        IReadOnlyDictionary<string, string> typeFileMap)
    {
        var returnTypes = endpoints
            .Where(e => e.ReturnType is not null)
            .Select(e => (TypeStr: TypeEmitter.EmitTypeString(e.ReturnType!), AssertName: GetAssertName(e.ReturnType!)))
            .DistinctBy(x => x.AssertName)
            .OrderBy(x => x.AssertName)
            .ToList();

        if (returnTypes.Count == 0)
        {
            return "";
        }

        var sb = new StringBuilder();
        sb.AppendLine("// Generated by Rivet — do not edit");
        sb.AppendLine("// This file is compiled by tsc + typia transformer to produce build/validators.js");
        sb.AppendLine();
        sb.AppendLine("import typia from \"typia\";");

        // Import types from their grouped source files
        var typeRefs = new HashSet<string>();
        foreach (var endpoint in endpoints.Where(e => e.ReturnType is not null))
        {
            TsType.CollectTypeRefs(endpoint.ReturnType!, typeRefs);
        }

        var importsByFile = typeRefs
            .Where(t => typeFileMap.ContainsKey(t))
            .GroupBy(t => typeFileMap[t])
            .OrderBy(g => g.Key);

        foreach (var group in importsByFile)
        {
            var names = string.Join(", ", group.Order());
            sb.AppendLine($"import type {{ {names} }} from \"./types/{group.Key}.js\";");
        }

        sb.AppendLine();

        foreach (var (typeStr, assertName) in returnTypes)
        {
            sb.AppendLine($"export const {assertName} = typia.createAssert<{typeStr}>();");
        }

        return sb.ToString();
    }

    /// <summary>
    /// Gets the assert function name for a return type by walking the TsType tree.
    /// </summary>
    public static string GetAssertName(TsType type) => $"assert{GetTypeSuffix(type)}";

    private static string GetTypeSuffix(TsType type) =>
        type switch
        {
            TsType.TypeRef r => r.Name,
            TsType.Primitive p => char.ToUpperInvariant(p.Name[0]) + p.Name[1..],
            TsType.Generic g => g.Name + string.Concat(g.TypeArguments.Select(GetTypeSuffix)),
            TsType.Array a => GetTypeSuffix(a.Element) + "Array",
            TsType.Nullable n => GetTypeSuffix(n.Inner),
            TsType.Brand b => b.Name,
            TsType.Dictionary d => "Record" + GetTypeSuffix(d.Value),
            TsType.StringUnion => "Union",
            _ => "Unknown",
        };
}
