using System.Text;
using Rivet.Tool.Model;

namespace Rivet.Tool.Emit;

/// <summary>
/// Emits validators.ts with typia.createAssert&lt;T&gt;() calls for each
/// endpoint return type. This file is inert until compiled by tsc + typia.
/// </summary>
public static class ValidatorEmitter
{
    public static string Emit(IReadOnlyList<TsEndpointDefinition> endpoints)
    {
        var returnTypes = endpoints
            .Where(e => e.ReturnType is not null)
            .Select(e => (TypeStr: TypeEmitter.EmitTypeString(e.ReturnType!), AssertName: GetAssertName(e.ReturnType!)))
            .DistinctBy(x => x.AssertName)
            .OrderBy(x => x.AssertName)
            .ToList();

        if (returnTypes.Count == 0)
        {
            return "";
        }

        var sb = new StringBuilder();
        sb.AppendLine("// Generated by Rivet — do not edit");
        sb.AppendLine("// This file is compiled by tsc + typia transformer to produce build/validators.js");
        sb.AppendLine();
        sb.AppendLine("import typia from \"typia\";");

        // Import the types from types.ts
        var typeNames = returnTypes
            .Select(x => GetBaseTypeName(x.TypeStr))
            .Distinct()
            .Order()
            .ToList();

        sb.AppendLine($"import type {{ {string.Join(", ", typeNames)} }} from \"./types.js\";");
        sb.AppendLine();

        foreach (var (typeStr, assertName) in returnTypes)
        {
            sb.AppendLine($"export const {assertName} = typia.createAssert<{typeStr}>();");
        }

        return sb.ToString();
    }

    /// <summary>
    /// Gets the assert function name for a return type.
    /// Arrays get "Array" suffix: assertMessageDto vs assertMessageDtoArray.
    /// </summary>
    public static string GetAssertName(TsType type) =>
        type switch
        {
            TsType.Array a => $"assert{GetBaseTypeName(TypeEmitter.EmitTypeString(a.Element))}Array",
            _ => $"assert{GetBaseTypeName(TypeEmitter.EmitTypeString(type))}",
        };

    private static string GetBaseTypeName(string typeName)
    {
        var name = typeName.TrimEnd('[', ']');
        var genericIdx = name.IndexOf('<');
        return genericIdx >= 0 ? name[..genericIdx] : name;
    }
}
