using System.Text;
using System.Text.Json;
using Rivet.Tool.Model;

namespace Rivet.Tool.Emit;

/// <summary>
/// Emits validators.ts with Zod-based validators using fromJSONSchema().
/// </summary>
public static class ZodValidatorEmitter
{
    /// <summary>
    /// Gets the assert function name for a return type by walking the TsType tree.
    /// </summary>
    public static string GetAssertName(TsType type) => $"assert{TsType.GetNameSuffix(type)}";

    public static string Emit(
        IReadOnlyList<TsEndpointDefinition> endpoints,
        IReadOnlyDictionary<string, string> typeFileMap)
    {
        var allTypes = endpoints
            .Where(e => e.ReturnType is not null)
            .Select(e => e.ReturnType!)
            .Concat(endpoints.SelectMany(e => e.Responses)
                .Where(r => r.DataType is not null)
                .Select(r => r.DataType!))
            .Concat(endpoints
                .Where(e => e.RequestType is not null)
                .Select(e => e.RequestType!))
            .Concat(endpoints
                .SelectMany(e => e.Params)
                .Where(p => p.Source == ParamSource.Body)
                .Select(p => p.Type));

        var validatedTypes = allTypes
            .Select(t => (
                Type: t,
                TypeStr: TypeEmitter.EmitTypeString(t),
                AssertName: GetAssertName(t)))
            .DistinctBy(x => x.AssertName)
            .OrderBy(x => x.AssertName)
            .ToList();

        if (validatedTypes.Count == 0)
        {
            return "";
        }

        var sb = new StringBuilder();
        sb.AppendLine("// Generated by Rivet — do not edit");
        sb.AppendLine();
        sb.AppendLine("import { fromJSONSchema, z } from \"zod\";");

        // Collect schema imports from base types
        var schemaImports = new HashSet<string>();
        foreach (var (type, _, _) in validatedTypes)
        {
            CollectSchemaImports(type, schemaImports);
        }

        if (schemaImports.Count > 0)
        {
            var sorted = schemaImports.Order().ToList();
            sb.AppendLine($"import {{ {string.Join(", ", sorted)} }} from \"./schemas.js\";");
        }

        // Import types for cast annotations
        var typeRefs = new HashSet<string>();
        foreach (var endpoint in endpoints.Where(e => e.ReturnType is not null))
        {
            TsType.CollectTypeRefs(endpoint.ReturnType!, typeRefs);
        }
        foreach (var response in endpoints.SelectMany(e => e.Responses).Where(r => r.DataType is not null))
        {
            TsType.CollectTypeRefs(response.DataType!, typeRefs);
        }
        foreach (var endpoint in endpoints.Where(e => e.RequestType is not null))
        {
            TsType.CollectTypeRefs(endpoint.RequestType!, typeRefs);
        }
        foreach (var param in endpoints.SelectMany(e => e.Params).Where(p => p.Source == ParamSource.Body))
        {
            TsType.CollectTypeRefs(param.Type, typeRefs);
        }

        var importsByFile = typeRefs
            .Where(t => typeFileMap.ContainsKey(t))
            .GroupBy(t => typeFileMap[t])
            .OrderBy(g => g.Key);

        foreach (var group in importsByFile)
        {
            var names = string.Join(", ", group.Order());
            sb.AppendLine($"import type {{ {names} }} from \"./types/{group.Key}.js\";");
        }

        sb.AppendLine();

        // Cached schema instances
        foreach (var (type, _, assertName) in validatedTypes)
        {
            var zodExpr = BuildZodExpression(type);
            sb.AppendLine($"const _{assertName} = {zodExpr};");
        }

        sb.AppendLine();

        // Assert functions
        foreach (var (_, typeStr, assertName) in validatedTypes)
        {
            sb.AppendLine($"export const {assertName} = (data: unknown): {typeStr} => _{assertName}.parse(data) as {typeStr};");
        }

        return sb.ToString();
    }

    /// <summary>
    /// Builds a Zod expression that validates the given TsType.
    /// Wraps fromJSONSchema() with z.array(), z.nullable() as needed.
    /// </summary>
    private static string BuildZodExpression(TsType type)
    {
        return type switch
        {
            TsType.TypeRef r => $"fromJSONSchema({r.Name}Schema)",
            TsType.Generic g => $"fromJSONSchema({JsonSchemaEmitter.MonomorphisedName(g)}Schema)",
            TsType.Brand b => $"fromJSONSchema({b.Name}Schema)",
            TsType.Array a => $"z.array({BuildZodExpression(a.Element)})",
            TsType.Nullable n => $"{BuildZodExpression(n.Inner)}.nullable()",
            TsType.Primitive p => BuildPrimitiveSchema(p),
            TsType.Dictionary d => $"z.record(z.string(), {BuildZodExpression(d.Value)})",
            TsType.StringUnion su => $"z.enum([{string.Join(", ", su.Members.Select(m => $"\"{m}\""))}])",
            TsType.IntUnion iu => $"z.union([{string.Join(", ", iu.Members.Select(m => $"z.literal({m})"))}])",
            TsType.InlineObject obj => $"z.object({{ {string.Join(", ", obj.Fields.Select(f => $"{TypeEmitter.QuoteIfNeeded(f.Name)}: {BuildZodExpression(f.Type)}"))} }})",
            TsType.TaggedUnion tu => $"z.discriminatedUnion(\"{tu.Discriminator}\", [{string.Join(", ", tu.Variants.Select(BuildTaggedUnionVariantExpression))}])",
            TsType.TypeParam => "z.unknown()",
            _ => "z.unknown()",
        };
    }

    private static string BuildTaggedUnionVariantExpression(TsType.TaggedUnionVariant variant)
    {
        return variant.Type switch
        {
            TsType.InlineObject obj => $"z.object({{ {string.Join(", ", obj.Fields.Select(f => $"{TypeEmitter.QuoteIfNeeded(f.Name)}: {BuildZodExpression(f.Type)}"))} }})",
            _ => BuildZodExpression(variant.Type),
        };
    }

    private static string BuildPrimitiveSchema(TsType.Primitive p)
    {
        if (p.Name == "unknown")
        {
            return "z.unknown()";
        }

        var schema = JsonSchemaEmitter.MapPrimitive(p);
        var json = JsonSerializer.Serialize(schema);
        return $"fromJSONSchema({json})";
    }

    /// <summary>
    /// Collects the schema import names needed for a type (the base TypeRef/Generic/Brand names).
    /// </summary>
    private static void CollectSchemaImports(TsType type, HashSet<string> imports)
    {
        switch (type)
        {
            case TsType.TypeRef r:
                imports.Add($"{r.Name}Schema");
                break;
            case TsType.Generic g:
                imports.Add($"{JsonSchemaEmitter.MonomorphisedName(g)}Schema");
                break;
            case TsType.Brand b:
                imports.Add($"{b.Name}Schema");
                break;
            case TsType.Array a:
                CollectSchemaImports(a.Element, imports);
                break;
            case TsType.Nullable n:
                CollectSchemaImports(n.Inner, imports);
                break;
            case TsType.Dictionary d:
                CollectSchemaImports(d.Value, imports);
                break;
            case TsType.InlineObject obj:
                foreach (var (_, fieldType) in obj.Fields)
                {
                    CollectSchemaImports(fieldType, imports);
                }
                break;
            case TsType.TaggedUnion tu:
                foreach (var variant in tu.Variants)
                {
                    CollectSchemaImports(variant.Type, imports);
                }
                break;
            case TsType.StringUnion:
            case TsType.IntUnion:
            case TsType.Primitive:
            case TsType.TypeParam:
                break;
        }
    }
}
