using System.Text;
using Rivet.Tool.Model;

namespace Rivet.Tool.Emit;

/// <summary>
/// Emits validators.ts with Zod-based validators using fromJSONSchema().
/// Same assertFoo interface as typia validators — clients don't need to know the backend.
/// </summary>
public static class ZodValidatorEmitter
{
    public static string Emit(
        IReadOnlyList<TsEndpointDefinition> endpoints,
        IReadOnlyDictionary<string, string> typeFileMap)
    {
        var allTypes = endpoints
            .Where(e => e.ReturnType is not null)
            .Select(e => e.ReturnType!)
            .Concat(endpoints.SelectMany(e => e.Responses)
                .Where(r => r.DataType is not null)
                .Select(r => r.DataType!));

        var returnTypes = allTypes
            .Select(t => (
                Type: t,
                TypeStr: TypeEmitter.EmitTypeString(t),
                AssertName: ValidatorEmitter.GetAssertName(t)))
            .DistinctBy(x => x.AssertName)
            .OrderBy(x => x.AssertName)
            .ToList();

        if (returnTypes.Count == 0)
        {
            return "";
        }

        var sb = new StringBuilder();
        sb.AppendLine("// Generated by Rivet — do not edit");
        sb.AppendLine();
        sb.AppendLine("import { fromJSONSchema, z } from \"zod\";");

        // Collect schema imports from base types
        var schemaImports = new HashSet<string>();
        foreach (var (type, _, _) in returnTypes)
        {
            CollectSchemaImports(type, schemaImports);
        }

        if (schemaImports.Count > 0)
        {
            var sorted = schemaImports.Order().ToList();
            sb.AppendLine($"import {{ {string.Join(", ", sorted)} }} from \"./schemas.js\";");
        }

        // Import types for cast annotations
        var typeRefs = new HashSet<string>();
        foreach (var endpoint in endpoints.Where(e => e.ReturnType is not null))
        {
            TsType.CollectTypeRefs(endpoint.ReturnType!, typeRefs);
        }
        foreach (var response in endpoints.SelectMany(e => e.Responses).Where(r => r.DataType is not null))
        {
            TsType.CollectTypeRefs(response.DataType!, typeRefs);
        }

        var importsByFile = typeRefs
            .Where(t => typeFileMap.ContainsKey(t))
            .GroupBy(t => typeFileMap[t])
            .OrderBy(g => g.Key);

        foreach (var group in importsByFile)
        {
            var names = string.Join(", ", group.Order());
            sb.AppendLine($"import type {{ {names} }} from \"./types/{group.Key}.js\";");
        }

        sb.AppendLine();

        // Cached schema instances
        foreach (var (type, _, assertName) in returnTypes)
        {
            var zodExpr = BuildZodExpression(type);
            sb.AppendLine($"const _{assertName} = {zodExpr};");
        }

        sb.AppendLine();

        // Assert functions — same interface as typia validators
        foreach (var (_, typeStr, assertName) in returnTypes)
        {
            sb.AppendLine($"export const {assertName} = (data: unknown): {typeStr} => _{assertName}.parse(data) as {typeStr};");
        }

        return sb.ToString();
    }

    /// <summary>
    /// Builds a Zod expression that validates the given TsType.
    /// Wraps fromJSONSchema() with z.array(), z.nullable() as needed.
    /// </summary>
    private static string BuildZodExpression(TsType type)
    {
        return type switch
        {
            TsType.TypeRef r => $"fromJSONSchema({r.Name}Schema as any)",
            TsType.Generic g => $"fromJSONSchema({JsonSchemaEmitter.MonomorphisedName(g)}Schema as any)",
            TsType.Brand b => $"fromJSONSchema({b.Name}Schema as any)",
            TsType.Array a => $"z.array({BuildZodExpression(a.Element)})",
            TsType.Nullable n => $"{BuildZodExpression(n.Inner)}.nullable()",
            TsType.Primitive p => BuildPrimitiveExpression(p),
            TsType.Dictionary d => $"z.record(z.string(), {BuildZodExpression(d.Value)})",
            TsType.StringUnion su => $"z.enum([{string.Join(", ", su.Members.Select(m => $"\"{m}\""))}])",
            TsType.InlineObject obj => $"z.object({{ {string.Join(", ", obj.Fields.Select(f => $"{f.Name}: {BuildZodExpression(f.Type)}"))} }})",
            TsType.TypeParam => "z.unknown()",
            _ => "z.unknown()",
        };
    }

    private static string BuildPrimitiveExpression(TsType.Primitive p)
    {
        return p.Name switch
        {
            "string" => "z.string()",
            "number" => "z.number()",
            "boolean" => "z.boolean()",
            _ => "z.unknown()",
        };
    }

    /// <summary>
    /// Collects the schema import names needed for a type (the base TypeRef/Generic/Brand names).
    /// </summary>
    private static void CollectSchemaImports(TsType type, HashSet<string> imports)
    {
        switch (type)
        {
            case TsType.TypeRef r:
                imports.Add($"{r.Name}Schema");
                break;
            case TsType.Generic g:
                imports.Add($"{JsonSchemaEmitter.MonomorphisedName(g)}Schema");
                break;
            case TsType.Brand b:
                imports.Add($"{b.Name}Schema");
                break;
            case TsType.Array a:
                CollectSchemaImports(a.Element, imports);
                break;
            case TsType.Nullable n:
                CollectSchemaImports(n.Inner, imports);
                break;
            case TsType.Dictionary d:
                CollectSchemaImports(d.Value, imports);
                break;
        }
    }
}
