// Generated by Rivet — do not edit

export type RivetConfig = {
  baseUrl: string;
  headers?: () => Record<string, string> | Promise<Record<string, string>>;
  fetch?: typeof fetch;
  onError?: (error: RivetError) => void;
};

export type RivetResult<T> = { status: number; data: T; response: Response };

export class RivetError extends Error {
  constructor(
    public readonly method: string,
    public readonly path: string,
    public readonly status: number,
    public readonly response: Response | undefined,
    public readonly body: unknown,
    options?: ErrorOptions,
  ) {
    super(`Rivet: ${method} ${path} returned ${status}`, options);
    this.name = "RivetError";
  }
}

let _config: RivetConfig = { baseUrl: "" };

export const configureRivet = (config: RivetConfig): void => {
  _config = config;
};

const parseBody = async (res: Response): Promise<unknown> => {
  const text = await res.text().catch(() => "");
  if (!text) return undefined;
  const ct = res.headers.get("content-type") ?? "";
  if (ct.includes("application/json")) {
    try { return JSON.parse(text); } catch { return text; }
  }
  return text;
};

export const rivetFetch = async <T>(
  method: string,
  path: string,
  options?: { body?: unknown; query?: Record<string, unknown>; unwrap?: boolean; blob?: boolean },
): Promise<T> => {
  const url = new URL(`${_config.baseUrl}${path}`);
  if (options?.query) {
    for (const [k, v] of Object.entries(options.query)) {
      if (v == null) continue;
      if (Array.isArray(v)) {
        for (const item of v) url.searchParams.append(k, String(item));
      } else {
        url.searchParams.set(k, String(v));
      }
    }
  }
  const headers: Record<string, string> = {
    ...(await _config.headers?.()),
  };
  const isFormData = typeof FormData !== "undefined" && options?.body instanceof FormData;
  if (options?.body != null && !isFormData) {
    headers["Content-Type"] = "application/json";
  }
  const f = _config.fetch ?? fetch;
  let res: Response;
  try {
    res = await f(url.toString(), {
      method,
      headers,
      body: options?.body != null ? (isFormData ? options.body as BodyInit : JSON.stringify(options.body)) : undefined,
    });
  } catch (err) {
    const error = new RivetError(method, path, 0, undefined, undefined, { cause: err });
    if (_config.onError) _config.onError(error);
    throw error;
  }
  if (options?.unwrap === false) {
    const body = options?.blob && res.ok ? await res.blob() : await parseBody(res);
    return { status: res.status, data: body, response: res } as T;
  }
  if (!res.ok) {
    const body = await parseBody(res);
    const error = new RivetError(method, path, res.status, res, body, {
      cause: new Error(`HTTP ${res.status}`),
    });
    if (_config.onError) _config.onError(error);
    throw error;
  }
  if (options?.blob) return (await res.blob()) as T;
  return (await parseBody(res)) as T;
};
