// Generated by Rivet — do not edit

export type RivetConfig = {
  baseUrl: string;
  headers?: () => Record<string, string> | Promise<Record<string, string>>;
  fetch?: (...args: Parameters<typeof fetch>) => Response | Promise<Response>;
  onError?: (error: RivetError) => void;
};

type RivetRawResult = { status: number; data: unknown; response: Response };
type RivetStatusMatch<TResult extends RivetRawResult, TStatus extends number> =
  Extract<TResult, { status: TStatus }> extends never
    ? TResult
    : Extract<TResult, { status: TStatus }>;

export type RivetResultMethods<TResult extends RivetRawResult> = {
  isInvalid(): boolean;
  isInformational(): boolean;
  isSuccessful(): boolean;
  isRedirection(): boolean;
  isClientError(): boolean;
  isServerError(): boolean;
  isOk(): this is RivetStatusMatch<TResult, 200>;
  isForbidden(): this is RivetStatusMatch<TResult, 403>;
  isNotFound(): this is RivetStatusMatch<TResult, 404>;
  isRedirect(location?: string): boolean;
  isEmpty(): boolean;
};

export type RivetResultOf<TResult extends RivetRawResult> = TResult & RivetResultMethods<TResult>;
export type RivetResult<T> = RivetResultOf<{ status: number; data: T; response: Response }>;

export class RivetError extends Error {
  constructor(
    public readonly method: string,
    public readonly path: string,
    public readonly status: number,
    public readonly response: Response | undefined,
    public readonly body: unknown,
    options?: ErrorOptions,
  ) {
    super(`Rivet: ${method} ${path} returned ${status}`, options);
    this.name = "RivetError";
  }
}

let _config: RivetConfig = { baseUrl: "" };

export const configureRivet = (config: RivetConfig): void => {
  _config = config;
};

export const getBaseUrl = (): string => _config.baseUrl;

const isInvalid = function (this: RivetRawResult): boolean {
  return this.status < 100 || this.status >= 600;
};

const isInformational = function (this: RivetRawResult): boolean {
  return this.status >= 100 && this.status < 200;
};

const isSuccessful = function (this: RivetRawResult): boolean {
  return this.status >= 200 && this.status < 300;
};

const isRedirection = function (this: RivetRawResult): boolean {
  return this.status >= 300 && this.status < 400;
};

const isClientError = function (this: RivetRawResult): boolean {
  return this.status >= 400 && this.status < 500;
};

const isServerError = function (this: RivetRawResult): boolean {
  return this.status >= 500 && this.status < 600;
};

const isOk = function (this: RivetRawResult): boolean {
  return this.status === 200;
};

const isForbidden = function (this: RivetRawResult): boolean {
  return this.status === 403;
};

const isNotFound = function (this: RivetRawResult): boolean {
  return this.status === 404;
};

const isRedirect = function (this: RivetRawResult, location?: string): boolean {
  if (!(this.status >= 300 && this.status < 400)) {
    return false;
  }

  if (location === undefined) {
    return true;
  }

  return this.response.headers.get("location") === location;
};

const isEmpty = function (this: RivetRawResult): boolean {
  return this.status === 204 || this.status === 304;
};

const attachRivetResultMethods = <TResult extends RivetRawResult>(
  result: TResult,
): RivetResultOf<TResult> => {
  if ("isOk" in result) {
    return result as RivetResultOf<TResult>;
  }

  Object.defineProperties(result, {
    isInvalid: { value: isInvalid, enumerable: false },
    isInformational: { value: isInformational, enumerable: false },
    isSuccessful: { value: isSuccessful, enumerable: false },
    isRedirection: { value: isRedirection, enumerable: false },
    isClientError: { value: isClientError, enumerable: false },
    isServerError: { value: isServerError, enumerable: false },
    isOk: { value: isOk, enumerable: false },
    isForbidden: { value: isForbidden, enumerable: false },
    isNotFound: { value: isNotFound, enumerable: false },
    isRedirect: { value: isRedirect, enumerable: false },
    isEmpty: { value: isEmpty, enumerable: false },
  });

  return result as RivetResultOf<TResult>;
};

const parseBody = async (res: Response): Promise<unknown> => {
  const text = await res.text().catch(() => "");
  if (!text) return undefined;
  const ct = res.headers.get("content-type") ?? "";
  if (ct.includes("application/json")) {
    try { return JSON.parse(text); } catch { return text; }
  }
  return text;
};

export const rivetFetch = async <T>(
  method: string,
  path: string,
  options?: { body?: unknown; query?: Record<string, unknown>; unwrap?: boolean; blob?: boolean },
): Promise<T> => {
  const url = new URL(`${_config.baseUrl}${path}`);
  if (options?.query) {
    for (const [k, v] of Object.entries(options.query)) {
      if (v == null) continue;
      if (Array.isArray(v)) {
        for (const item of v) url.searchParams.append(k, String(item));
      } else {
        url.searchParams.set(k, String(v));
      }
    }
  }
  const headers: Record<string, string> = {
    ...(await _config.headers?.()),
  };
  const isFormData = typeof FormData !== "undefined" && options?.body instanceof FormData;
  if (options?.body != null && !isFormData) {
    headers["Content-Type"] = "application/json";
  }
  const f = _config.fetch ?? fetch;
  let res: Response;
  try {
    res = await Promise.resolve(f(url.toString(), {
      method,
      headers,
      body: options?.body != null ? (isFormData ? options.body as BodyInit : JSON.stringify(options.body)) : undefined,
    }));
  } catch (err) {
    const error = new RivetError(method, path, 0, undefined, undefined, { cause: err });
    if (_config.onError) _config.onError(error);
    throw error;
  }
  if (options?.unwrap === false) {
    const body = options?.blob && res.ok ? await res.blob() : await parseBody(res);
    return attachRivetResultMethods({ status: res.status, data: body, response: res }) as T;
  }
  if (!res.ok) {
    const body = await parseBody(res);
    const error = new RivetError(method, path, res.status, res, body, {
      cause: new Error(`HTTP ${res.status}`),
    });
    if (_config.onError) _config.onError(error);
    throw error;
  }
  if (options?.blob) return (await res.blob()) as T;
  return (await parseBody(res)) as T;
};
