// Generated by Rivet — do not edit

import type { core } from "zod";
type JSONSchema = core.JSONSchema.JSONSchema;

const $defs: Record<string, JSONSchema> = {
  "AddressDto": {
    "type": "object",
    "properties": {
      "street": {
        "type": "string"
      },
      "city": {
        "type": "string"
      }
    },
    "required": [
      "street",
      "city"
    ]
  },
  "UserDto": {
    "type": "object",
    "properties": {
      "name": {
        "type": "string"
      },
      "age": {
        "type": "number"
      },
      "address": {
        "$ref": "#/$defs/AddressDto"
      }
    },
    "required": [
      "name",
      "age",
      "address"
    ]
  }
};

export const AddressDtoSchema: JSONSchema = { "$ref": "#/$defs/AddressDto", "$defs": $defs };
export const UserDtoSchema: JSONSchema = { "$ref": "#/$defs/UserDto", "$defs": $defs };
