// Generated by Rivet — do not edit

const $defs = {
  "AddressDto": {
    "type": "object",
    "properties": {
      "street": {
        "type": "string"
      },
      "city": {
        "type": "string"
      }
    },
    "required": [
      "street",
      "city"
    ]
  },
  "UserDto": {
    "type": "object",
    "properties": {
      "name": {
        "type": "string"
      },
      "age": {
        "type": "number"
      },
      "address": {
        "$ref": "#/$defs/AddressDto"
      }
    },
    "required": [
      "name",
      "age",
      "address"
    ]
  }
} as const;

export const AddressDtoSchema = { "$ref": "#/$defs/AddressDto", "$defs": $defs } as const;
export const UserDtoSchema = { "$ref": "#/$defs/UserDto", "$defs": $defs } as const;
