using Rivet.Tool.Analysis;
using Rivet.Tool.Emit;

namespace Rivet.Tests;

public sealed class TypeEmitterTests
{
    private static string Generate(string source)
    {
        var compilation = CompilationHelper.CreateCompilation(source);
        var definitions = TypeWalker.Walk(compilation);
        return TypeEmitter.Emit(definitions);
    }

    [Fact]
    public void Primitives_MapCorrectly()
    {
        var source = """
            using System;
            using Rivet;

            namespace Test;

            [RivetType]
            public sealed record SimpleDto(
                string Name,
                int Count,
                long BigCount,
                double Rate,
                decimal Price,
                bool IsActive,
                Guid Id,
                DateTime CreatedAt,
                DateTimeOffset UpdatedAt,
                DateOnly BirthDate);
            """;

        var result = Generate(source);

        Assert.Equal(
            """
            // Generated by Rivet — do not edit

            export type SimpleDto = {
              name: string;
              count: number;
              bigCount: number;
              rate: number;
              price: number;
              isActive: boolean;
              id: string;
              createdAt: string;
              updatedAt: string;
              birthDate: string;
            };

            """,
            result);
    }

    [Fact]
    public void NullableValueType_MapsToUnion()
    {
        var source = """
            using Rivet;

            namespace Test;

            [RivetType]
            public sealed record WithNullables(int? MaybeCount, bool? MaybeActive);
            """;

        var result = Generate(source);

        Assert.Contains("maybeCount: number | null;", result);
        Assert.Contains("maybeActive: boolean | null;", result);
    }

    [Fact]
    public void NullableReferenceType_MapsToUnion()
    {
        var source = """
            using Rivet;

            namespace Test;

            [RivetType]
            public sealed record WithNullableRef(string? MaybeName);
            """;

        var result = Generate(source);

        Assert.Contains("maybeName: string | null;", result);
    }

    [Fact]
    public void Collections_MapToArray()
    {
        var source = """
            using System;
            using System.Collections.Generic;
            using Rivet;

            namespace Test;

            [RivetType]
            public sealed record WithCollections(
                List<string> Names,
                int[] Counts,
                IEnumerable<Guid> Ids,
                IReadOnlyList<bool> Flags);
            """;

        var result = Generate(source);

        Assert.Contains("names: string[];", result);
        Assert.Contains("counts: number[];", result);
        Assert.Contains("ids: string[];", result);
        Assert.Contains("flags: boolean[];", result);
    }

    [Fact]
    public void Dictionary_MapsToRecord()
    {
        var source = """
            using Rivet;
            using System.Collections.Generic;

            namespace Test;

            [RivetType]
            public sealed record WithDict(Dictionary<string, int> Scores);
            """;

        var result = Generate(source);

        Assert.Contains("scores: Record<string, number>;", result);
    }

    [Fact]
    public void Enum_MapsToStringUnion()
    {
        var source = """
            using Rivet;

            namespace Test;

            public enum Status { Draft, Active, Closed }

            [RivetType]
            public sealed record WithEnum(Status CurrentStatus);
            """;

        var result = Generate(source);

        Assert.Contains("""currentStatus: "Draft" | "Active" | "Closed";""", result);
    }

    [Fact]
    public void NestedRecord_DiscoveredTransitively()
    {
        var source = """
            using Rivet;

            namespace Test;

            public sealed record Address(string Street, string City);

            [RivetType]
            public sealed record PersonDto(string Name, Address HomeAddress);
            """;

        var result = Generate(source);

        // Both types should be emitted
        Assert.Contains("export type PersonDto = {", result);
        Assert.Contains("export type Address = {", result);
        // PersonDto references Address by name
        Assert.Contains("homeAddress: Address;", result);
        // Address has its own properties
        Assert.Contains("street: string;", result);
        Assert.Contains("city: string;", result);
    }

    [Fact]
    public void OptionalProperty_NullableNonRequired()
    {
        var source = """
            using Rivet;

            namespace Test;

            [RivetType]
            public sealed record WithOptional(string Required, string? Optional);
            """;

        var result = Generate(source);

        Assert.Contains("required: string;", result);
        Assert.Contains("optional: string | null;", result);
    }

    [Fact]
    public void NullableArray_WrapsInParens()
    {
        var source = """
            using Rivet;
            using System.Collections.Generic;

            namespace Test;

            [RivetType]
            public sealed record WithNullableArray(List<string?> MaybeNames);
            """;

        var result = Generate(source);

        Assert.Contains("maybeNames: (string | null)[];", result);
    }

    [Fact]
    public void MultipleRivetTypes_AllEmitted()
    {
        var source = """
            using Rivet;

            namespace Test;

            [RivetType]
            public sealed record CommandA(string Name);

            [RivetType]
            public sealed record CommandB(int Count);
            """;

        var result = Generate(source);

        Assert.Contains("export type CommandA = {", result);
        Assert.Contains("export type CommandB = {", result);
    }

    [Fact]
    public void NoRivetTypes_EmitsHeaderOnly()
    {
        var source = """
            namespace Test;

            public sealed record NotAttributed(string Name);
            """;

        var result = Generate(source);

        Assert.Equal(
            """
            // Generated by Rivet — do not edit


            """,
            result);
    }

    [Fact]
    public void ComplexScenario_MatchesExpectedOutput()
    {
        var source = """
            using Rivet;
            using System;
            using System.Collections.Generic;

            namespace Test;

            public enum MessageVisibility { Internal, Public }

            [RivetType]
            public sealed record CreateMessageCommand(
                Guid SubmissionId,
                string Body,
                MessageVisibility Visibility);

            [RivetType]
            public sealed record MessageDto(
                Guid Id,
                string Body,
                string AuthorName,
                DateTime CreatedAt);
            """;

        var result = Generate(source);

        Assert.Equal(
            """
            // Generated by Rivet — do not edit

            export type CreateMessageCommand = {
              submissionId: string;
              body: string;
              visibility: "Internal" | "Public";
            };

            export type MessageDto = {
              id: string;
              body: string;
              authorName: string;
              createdAt: string;
            };

            """,
            result);
    }
}
