using System.Reflection;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Rivet;

/// <summary>
/// Marks a record as an UNDISCRIMINATED union wrapper: at most one of its
/// optional properties is set, and on the wire the value is the BARE variant —
/// never the wrapper object. The OpenAPI emitter renders these as a
/// <c>oneOf</c> of the property types, and (being a JsonConverterAttribute)
/// serialization unwraps/rewraps to match, so the runtime and the emitted
/// spec tell the same story. Generated by the OpenAPI importer for
/// primitive/mixed <c>oneOf</c> schemas that have no discriminator.
/// </summary>
[AttributeUsage(AttributeTargets.Class | AttributeTargets.Struct)]
public sealed class RivetUnionAttribute : JsonConverterAttribute
{
    public override JsonConverter? CreateConverter(Type typeToConvert) =>
        (JsonConverter?)
            Activator.CreateInstance(
                typeof(RivetUnionJsonConverter<>).MakeGenericType(typeToConvert)
            );
}

/// <summary>
/// Serializes a [RivetUnion] wrapper as its single non-null variant value;
/// deserializes by matching the JSON kind against the variant property types
/// in declaration order. Wrappers are positional records whose parameters
/// mirror their properties (the shape the importer generates).
/// </summary>
public sealed class RivetUnionJsonConverter<T> : JsonConverter<T>
{
    private static readonly PropertyInfo[] _variantProperties = typeof(T)
        .GetProperties(BindingFlags.Public | BindingFlags.Instance)
        .Where(property => property.CanRead)
        .ToArray();

    public override T? Read(
        ref Utf8JsonReader reader,
        Type typeToConvert,
        JsonSerializerOptions options
    )
    {
        using var document = JsonDocument.ParseValue(ref reader);
        var element = document.RootElement;

        foreach (var property in _variantProperties)
        {
            if (!KindMatches(element, property.PropertyType))
            {
                continue;
            }

            object? value;
            try
            {
                value = element.Deserialize(property.PropertyType, options);
            }
            catch (JsonException)
            {
                continue;
            }

            return Construct(property, value);
        }

        throw new JsonException(
            $"Value does not match any variant of union wrapper '{typeof(T).Name}'."
        );
    }

    public override void Write(Utf8JsonWriter writer, T value, JsonSerializerOptions options)
    {
        foreach (var property in _variantProperties)
        {
            var variant = property.GetValue(value);
            if (variant is not null)
            {
                JsonSerializer.Serialize(writer, variant, property.PropertyType, options);
                return;
            }
        }

        writer.WriteNullValue();
    }

    private static bool KindMatches(JsonElement element, Type propertyType)
    {
        var underlying = Nullable.GetUnderlyingType(propertyType) ?? propertyType;

        if (underlying == typeof(string))
        {
            return element.ValueKind == JsonValueKind.String;
        }

        if (underlying == typeof(bool))
        {
            return element.ValueKind is JsonValueKind.True or JsonValueKind.False;
        }

        if (underlying.IsPrimitive || underlying == typeof(decimal))
        {
            return element.ValueKind == JsonValueKind.Number;
        }

        // Complex variants: object/array shapes; let Deserialize decide.
        return element.ValueKind is JsonValueKind.Object or JsonValueKind.Array;
    }

    private static T Construct(PropertyInfo matched, object? value)
    {
        // The importer generates positional records: one constructor whose
        // parameters correspond 1:1 (by name, case-insensitively) with the
        // variant properties.
        var constructor = typeof(T)
            .GetConstructors()
            .OrderByDescending(candidate => candidate.GetParameters().Length)
            .First();

        var arguments = constructor
            .GetParameters()
            .Select(parameter =>
                string.Equals(parameter.Name, matched.Name, StringComparison.OrdinalIgnoreCase)
                    ? value
                    : null
            )
            .ToArray();

        return (T)constructor.Invoke(arguments);
    }
}
